CREATE TYPE [AVL].[ADM_TVP_WorkItemDetails] AS TABLE (
    [WorkItemType]      BIGINT          NULL,
    [WorkItemID]        NVARCHAR (100)  NULL,
    [WorkItemTitle]     NVARCHAR (MAX)  NULL,
    [Description]       NVARCHAR (MAX)  NULL,
    [Status]            BIGINT          NULL,
    [Activity]          NVARCHAR (250)  NULL,
    [Application]       BIGINT          NULL,
    [CreatedDate]       DATETIME        NULL,
    [CreatedBy]         NVARCHAR (50)   NULL,
    [Assignee]          NVARCHAR (50)   NULL,
    [ServiceId]         BIGINT          NULL,
    [PriorityMapId]     BIGINT          NULL,
    [SeverityMapId]     BIGINT          NULL,
    [Risk]              NVARCHAR (250)  NULL,
    [Story]             INT             NULL,
    [ActualStartDate]   DATETIME        NULL,
    [ActualEndDate]     DATETIME        NULL,
    [PlannedStartDate]  DATETIME        NULL,
    [PlannedEndDate]    DATETIME        NULL,
    [EstimationPoints]  NVARCHAR (100)  NULL,
    [PlannedEstimate]   DECIMAL (18, 2) NULL,
    [AcutalEffort]      DECIMAL (18, 2) NULL,
    [SprintDetails]     BIGINT          NULL,
    [TargetDate]        DATETIME        NULL,
    [ModifiedDate]      DATETIME        NULL,
    [ModifiedBy]        NVARCHAR (50)   NULL,
    [LinkedParentID]    NVARCHAR (100)  NULL,
    [LinkedChildID]     NVARCHAR (10)   NULL,
    [Theme]             BIGINT          NULL,
    [IsMilestonemet]    BIT             NULL,
    [BugPhaseTypeMapId] SMALLINT        NULL);

