CREATE TYPE [AVL].[SaveErrorLogTicketDetails] AS TABLE (
    [TicketID]                    VARCHAR (100)  NULL,
    [TicketDescription]           NVARCHAR (MAX) NULL,
    [ApplicationID]               INT            NULL,
    [Application]                 VARCHAR (MAX)  NULL,
    [TicketTypeID]                INT            NULL,
    [TicketType]                  VARCHAR (MAX)  NULL,
    [Priority]                    VARCHAR (MAX)  NULL,
    [PriorityID]                  INT            NULL,
    [StatusID]                    INT            NULL,
    [Status]                      VARCHAR (MAX)  NULL,
    [severityID]                  INT            NULL,
    [Severity]                    VARCHAR (MAX)  NULL,
    [CauseCodeID]                 INT            NULL,
    [Causecode]                   VARCHAR (MAX)  NULL,
    [ResolutionID]                INT            NULL,
    [ResolutionCode]              VARCHAR (MAX)  NULL,
    [DebtClassificationId]        INT            NULL,
    [DebtClassification]          VARCHAR (MAX)  NULL,
    [AvoidableFlagID]             INT            NULL,
    [AvoidableFlag]               VARCHAR (MAX)  NULL,
    [ResidualDebtID]              INT            NULL,
    [ResidualDebt]                VARCHAR (MAX)  NULL,
    [OpenDate]                    DATETIME       NULL,
    [ProjectID]                   INT            NULL,
    [AssignmentGroupID]           INT            NULL,
    [TowerID]                     INT            NULL,
    [MTicketDescription]          NVARCHAR (MAX) NULL,
    [IsTicketDescriptionModified] BIT            NULL,
    [IsPartiallyAutomated]        INT            NULL);

