CREATE TYPE [AVL].[TicketUploadTrackType] AS TABLE (
    [ProjectID]                   BIGINT        NULL,
    [EmployeeID]                  VARCHAR (50)  NULL,
    [Mode]                        INT           NULL,
    [FileName]                    VARCHAR (MAX) NULL,
    [IsColumnMappingValidated]    BIT           DEFAULT ((1)) NULL,
    [MndColValBeginTime]          DATETIME      NULL,
    [MndColValEndTime]            DATETIME      NULL,
    [NonMndColValBeginTime]       DATETIME      NULL,
    [NonMndColValEndTime]         DATETIME      NULL,
    [NullValUpdateBeginTime]      DATETIME      NULL,
    [NullValUpdateEndTime]        DATETIME      NULL,
    [MasterValuesUpdateBeginTime] DATETIME      NULL,
    [MasterValuesUpdateEndTime]   DATETIME      NULL,
    [BLErrorMessage]              VARCHAR (MAX) NULL,
    [DBErrorMessage]              VARCHAR (MAX) NULL,
    [TotalRecordsInExcel]         INT           DEFAULT ((0)) NULL,
    [TotalValidRecords]           INT           DEFAULT ((0)) NULL,
    [TotalDuplicateRecords]       INT           DEFAULT ((0)) NULL,
    [TotalRejectedRecords]        INT           DEFAULT ((0)) NULL,
    [IsActive]                    BIT           DEFAULT ((1)) NULL,
    [CreatedBy]                   VARCHAR (50)  NULL,
    [CreatedDate]                 DATETIME      DEFAULT (getdate()) NULL,
    [ModifiedBy]                  VARCHAR (50)  NULL,
    [ModifiedDate]                DATETIME      NULL,
    [StoredProcedureStartTime]    DATETIME      NULL,
    [StoredProcedureEndTime]      DATETIME      NULL);

