CREATE TYPE [AVL].[TVP_OnPremGovernanceMetrics] AS TABLE (
    [AccountID]                                VARCHAR (1000) NOT NULL,
    [ProjectID]                                VARCHAR (1000) NOT NULL,
    [ProjectName]                              VARCHAR (1000) NOT NULL,
    [Month]                                    VARCHAR (1000) NOT NULL,
    [Year]                                     VARCHAR (1000) NOT NULL,
    [AllDebtClassifiedTicketCount]             VARCHAR (1000) NULL,
    [EligibleTicketCountForDebtClassification] VARCHAR (1000) NULL,
    [MLDDAutoClassifiedTicketCount]            VARCHAR (1000) NULL,
    [BoTTicketCount]                           VARCHAR (1000) NULL,
    [PartiallyAutomatedTicketCount]            VARCHAR (1000) NULL,
    [ClosedATicketCount]                       VARCHAR (1000) NULL,
    [ClosedHTicketCount]                       VARCHAR (1000) NULL,
    [TotalEffortofChildATickets]               VARCHAR (1000) NULL,
    [CompletedMonthsofATicket]                 VARCHAR (1000) NULL,
    [TotalEffortofChildHTickets]               VARCHAR (1000) NULL,
    [CompletedMonthsofHTicket]                 VARCHAR (1000) NULL,
    [HChidTicketCount]                         VARCHAR (1000) NULL,
    [OperationalTicketCount]                   VARCHAR (1000) NULL,
    [KnowledgeTicketCount]                     VARCHAR (1000) NULL,
    [FunctionalTicketCount]                    VARCHAR (1000) NULL,
    [TechnicalTicketCount]                     VARCHAR (1000) NULL,
    [EnvironmentalTicketCount]                 VARCHAR (1000) NULL,
    [ResidualTicketCount]                      VARCHAR (1000) NULL,
    [CreatedATicketCount]                      VARCHAR (1000) NULL,
    [CreatedHTicketCount]                      VARCHAR (1000) NULL,
    [InProgressATicketCount]                   VARCHAR (1000) NULL,
    [InProgressHTicketCount]                   VARCHAR (1000) NULL,
    [DormantATicketsClosedCount]               VARCHAR (1000) NULL,
    [DormantHTicketsClosedCount]               VARCHAR (1000) NULL,
    [CancelledATicketCount]                    VARCHAR (1000) NULL,
    [CancelledHTicketCount]                    VARCHAR (1000) NULL,
    [AvoidableIncidentCount]                   VARCHAR (1000) NULL,
    [UnAvoidableIncidentCount]                 VARCHAR (1000) NULL);

