CREATE TYPE [AVL].[TVP_InfraTowerAttributes] AS TABLE (
    [CustomerID]                 BIGINT        NULL,
    [InfraTowerTransactionID]    BIGINT        NOT NULL,
    [Type]                       NVARCHAR (50) NULL,
    [Item]                       NVARCHAR (50) NULL,
    [CopyOrSerialNumber]         NVARCHAR (50) NULL,
    [ModelNumberHardware]        NVARCHAR (50) NULL,
    [WarrantyExpiryDate]         DATETIME      NULL,
    [SourceSupplier]             NVARCHAR (50) NULL,
    [License]                    NVARCHAR (50) NULL,
    [SupplyDate]                 DATE          NULL,
    [AcceptedDate]               DATE          NULL,
    [StatusScheduled]            NVARCHAR (50) NULL,
    [SLA]                        INT           NULL,
    [ServicePackAndPatchDetails] NVARCHAR (50) NULL,
    [AdminGroups]                NVARCHAR (50) NULL,
    [UserGroups]                 NVARCHAR (50) NULL,
    [IPAddress]                  NVARCHAR (50) NULL,
    [CreatedBy]                  NVARCHAR (50) NULL,
    [Name]                       NVARCHAR (50) NULL,
    [ProductName]                NVARCHAR (50) NULL,
    [Function]                   NVARCHAR (50) NULL,
    [Owner]                      NVARCHAR (50) NULL,
    [Version]                    NVARCHAR (50) NULL,
    [Contact]                    NVARCHAR (50) NULL,
    [Category]                   NVARCHAR (50) NULL,
    [ProductionDate]             DATE          NULL,
    [Hotfix]                     NVARCHAR (50) NULL,
    [ServicePack]                NVARCHAR (50) NULL,
    [Supplier]                   NVARCHAR (50) NULL,
    [Status]                     NVARCHAR (50) NULL,
    [Location]                   NVARCHAR (50) NULL,
    [NatureOfEmployment]         NVARCHAR (50) NULL);

