CREATE TYPE [AVL].[TVP_UpdateAttributeDetails] AS TABLE (
    [TicketID]                VARCHAR (100)   NULL,
    [serviceid]               INT             NULL,
    [projectId]               BIGINT          NULL,
    [Priority]                BIGINT          NULL,
    [Severity]                BIGINT          NULL,
    [Assignedto]              VARCHAR (100)   NULL,
    [ReleaseType]             BIGINT          NULL,
    [PlannedEffort]           DECIMAL (20, 2) NULL,
    [EstimatedWorkSize]       DECIMAL (20, 2) NULL,
    [Ticketcreatedate]        DATETIME        NULL,
    [PlannedStartDateandTime] DATETIME        NULL,
    [PlannedEndDate]          DATETIME        NULL,
    [ActualStartdateTime]     DATETIME        NULL,
    [ActualEnddateTime]       DATETIME        NULL,
    [ReopenDate]              DATETIME        NULL,
    [RejectedTimeStamp]       DATETIME        NULL,
    [CloseDate]               DATETIME        NULL,
    [ReleaseDate]             DATETIME        NULL,
    [KEDBAvailableIndicator]  BIGINT          NULL,
    [KEDBUpdatedAdded]        BIGINT          NULL,
    [RCAID]                   VARCHAR (20)    NULL,
    [PlannedDuration]         DECIMAL (26, 5) NULL,
    [ActualDuration]          DECIMAL (26, 5) NULL,
    [MetResponseSLA]          VARCHAR (100)   NULL,
    [MetAcknowledgementSLA]   VARCHAR (100)   NULL,
    [MetResolution]           VARCHAR (100)   NULL,
    [TicketDescription]       NVARCHAR (MAX)  NULL,
    [NatureOfTheTicket]       VARCHAR (50)    NULL,
    [Application]             BIGINT          NULL,
    [TicketCreatedBy]         VARCHAR (50)    NULL,
    [KEDBPath]                VARCHAR (MAX)   NULL,
    [StartedDateTime]         DATETIME        NULL,
    [WIPDateTime]             DATETIME        NULL,
    [OnHoldDateTime]          DATETIME        NULL,
    [CompletedDateTime]       DATETIME        NULL,
    [CancelledDateTime]       DATETIME        NULL,
    [AssignedTimeStamp]       DATETIME        NULL,
    [ResolutionCode]          BIGINT          NULL,
    [DebtClassificationId]    BIGINT          NULL,
    [Resolutionmethod]        BIGINT          NULL,
    [CauseCode]               BIGINT          NULL,
    [ActualEffort]            DECIMAL (20, 2) NULL,
    [TicketOpenDate]          DATETIME        NULL);

