CREATE TABLE [BCS].[BidRulesEncrypted] (
    [RULE_ID]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [PRIORITY]        BIGINT         NOT NULL,
    [WORK_PATTERN]    NVARCHAR (MAX) NOT NULL,
    [CAUSE_CODE]      NVARCHAR (MAX) NOT NULL,
    [RESOLUTION_CODE] NVARCHAR (MAX) NOT NULL,
    [SERVICE_NAME]    NVARCHAR (MAX) NOT NULL,
    PRIMARY KEY CLUSTERED ([RULE_ID] ASC)
);

