CREATE TABLE [ML].[CL_TRN_InfraTicketValidation] (
    [ID]                           BIGINT         IDENTITY (1, 1) NOT NULL,
    [ProjectID]                    BIGINT         NULL,
    [TicketID]                     NVARCHAR (500) NULL,
    [TicketDescription]            NVARCHAR (MAX) NULL,
    [TowerID]                      INT            NOT NULL,
    [DebtClassificationID]         BIGINT         NULL,
    [AvoidableFlagID]              INT            NULL,
    [ResidualDebtID]               BIGINT         NULL,
    [CauseCodeID]                  BIGINT         NULL,
    [ResolutionCodeID]             BIGINT         NULL,
    [OptionalFieldProj]            NVARCHAR (MAX) NULL,
    [CreatedBy]                    NVARCHAR (50)  NOT NULL,
    [CreatedDate]                  DATETIME       NOT NULL,
    [ModifiedBy]                   NVARCHAR (50)  NULL,
    [ModifiedDate]                 DATETIME       NULL,
    [IsDeleted]                    BIT            NOT NULL,
    [TicketDescriptionBasePattern] NVARCHAR (500) DEFAULT (NULL) NULL,
    [TicketDescriptionSubPattern]  NVARCHAR (500) DEFAULT (NULL) NULL,
    [ResolutionRemarksBasePattern] NVARCHAR (500) DEFAULT (NULL) NULL,
    [ResolutionRemarksSubPattern]  NVARCHAR (500) DEFAULT (NULL) NULL,
    CONSTRAINT [PK_CLInfraTicketID] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_InfraTicketValidationProjectID] FOREIGN KEY ([ProjectID]) REFERENCES [AVL].[MAS_ProjectMaster] ([ProjectID]),
    CONSTRAINT [FK_TVAvoidableID] FOREIGN KEY ([AvoidableFlagID]) REFERENCES [AVL].[DEBT_MAS_AvoidableFlag] ([AvoidableFlagID]),
    CONSTRAINT [FK_TVCauseID] FOREIGN KEY ([CauseCodeID]) REFERENCES [AVL].[DEBT_MAP_CauseCode] ([CauseID]),
    CONSTRAINT [FK_TVDebtClassificationID] FOREIGN KEY ([DebtClassificationID]) REFERENCES [AVL].[DEBT_MAS_DebtClassificationInfra] ([DebtClassificationID]),
    CONSTRAINT [FK_TVResdiualID] FOREIGN KEY ([ResidualDebtID]) REFERENCES [AVL].[DEBT_MAS_ResidualDebt] ([ResidualDebtID]),
    CONSTRAINT [FK_TVResolutionID] FOREIGN KEY ([ResolutionCodeID]) REFERENCES [AVL].[DEBT_MAP_ResolutionCode] ([ResolutionID])
);

