CREATE TABLE [ML].[CL_TRN_PatternValidation] (
    [ID]                          BIGINT          IDENTITY (1, 1) NOT NULL,
    [ContLearningID]              INT             NOT NULL,
    [ProjectID]                   BIGINT          NOT NULL,
    [ApplicationID]               BIGINT          NOT NULL,
    [ApplicationTypeID]           INT             NULL,
    [TechnologyID]                INT             NULL,
    [TicketPattern]               NVARCHAR (1000) NULL,
    [TicketSubPattern]            NVARCHAR (1000) NULL,
    [AdditionalPattern]           NVARCHAR (1000) NULL,
    [AdditionalSubPattern]        NVARCHAR (1000) NULL,
    [PatternsOrigin]              NVARCHAR (500)  NOT NULL,
    [IsApprovedPatternsConflict]  CHAR (1)        NULL,
    [ILRuleID]                    BIGINT          NULL,
    [IsDefaultRuleSelected]       CHAR (1)        NULL,
    [MLResidualFlagID]            INT             NULL,
    [MLDebtClassificationID]      INT             NULL,
    [MLAvoidableFlagID]           INT             NULL,
    [MLCauseCodeID]               INT             NULL,
    [MLAccuracy]                  DECIMAL (18, 2) NULL,
    [TicketOccurence]             INT             NULL,
    [AnalystResidualFlagID]       INT             NULL,
    [AnalystResolutionCodeID]     INT             NULL,
    [AnalystCauseCodeID]          INT             NULL,
    [AnalystDebtClassificationID] INT             NULL,
    [AnalystAvoidableFlagID]      INT             NULL,
    [SMEComments]                 NVARCHAR (4000) NULL,
    [SMEResidualFlagID]           INT             NULL,
    [SMEDebtClassificationID]     INT             NULL,
    [SMEAvoidableFlagID]          INT             NULL,
    [SMECauseCodeID]              INT             NULL,
    [IsApprovedOrMute]            INT             NULL,
    [CreatedBy]                   NVARCHAR (20)   NOT NULL,
    [CreatedDate]                 DATETIME        NOT NULL,
    [ModifiedBy]                  NVARCHAR (20)   NULL,
    [ModifiedDate]                DATETIME        NULL,
    [IsDeleted]                   BIT             NOT NULL,
    [IsCLSignOff]                 BIT             NULL,
    [MLResolutionCodeID]          INT             NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

