CREATE TABLE [ML].[CL_TRN_InfraPatternValidation] (
    [ID]                          BIGINT          IDENTITY (1, 1) NOT NULL,
    [ContLearningID]              BIGINT          NULL,
    [ProjectID]                   BIGINT          NOT NULL,
    [TowerID]                     BIGINT          NOT NULL,
    [TechnologyID]                INT             NULL,
    [TicketPattern]               NVARCHAR (1000) NULL,
    [TicketSubPattern]            NVARCHAR (1000) NULL,
    [AdditionalPattern]           NVARCHAR (1000) NULL,
    [AdditionalSubPattern]        NVARCHAR (1000) NULL,
    [PatternsOrigin]              NVARCHAR (500)  NOT NULL,
    [IsApprovedPatternsConflict]  CHAR (1)        NULL,
    [ILRuleID]                    BIGINT          NULL,
    [IsDefaultRuleSelected]       CHAR (1)        NULL,
    [MLResidualFlagID]            BIGINT          NULL,
    [MLDebtClassificationID]      BIGINT          NULL,
    [MLAvoidableFlagID]           INT             NULL,
    [MLCauseCodeID]               BIGINT          NULL,
    [MLAccuracy]                  DECIMAL (18, 2) NULL,
    [TicketOccurence]             INT             NULL,
    [AnalystResidualFlagID]       BIGINT          NULL,
    [AnalystResolutionCodeID]     BIGINT          NULL,
    [AnalystCauseCodeID]          BIGINT          NULL,
    [AnalystDebtClassificationID] BIGINT          NULL,
    [AnalystAvoidableFlagID]      INT             NULL,
    [SMEComments]                 NVARCHAR (4000) NULL,
    [SMEResidualFlagID]           BIGINT          NULL,
    [SMEDebtClassificationID]     BIGINT          NULL,
    [SMEAvoidableFlagID]          INT             NULL,
    [SMECauseCodeID]              BIGINT          NULL,
    [IsApprovedOrMute]            INT             NULL,
    [CreatedBy]                   NVARCHAR (50)   NOT NULL,
    [CreatedDate]                 DATETIME        NOT NULL,
    [ModifiedBy]                  NVARCHAR (50)   NULL,
    [ModifiedDate]                DATETIME        NULL,
    [IsDeleted]                   BIT             NOT NULL,
    [IsCLSignOff]                 BIT             NULL,
    [MLResolutionCodeID]          BIGINT          NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_AnalystAvoidableID] FOREIGN KEY ([AnalystAvoidableFlagID]) REFERENCES [AVL].[DEBT_MAS_AvoidableFlag] ([AvoidableFlagID]),
    CONSTRAINT [FK_AnalystCauseID] FOREIGN KEY ([AnalystCauseCodeID]) REFERENCES [AVL].[DEBT_MAP_CauseCode] ([CauseID]),
    CONSTRAINT [FK_AnalystDebtClassificationID] FOREIGN KEY ([AnalystDebtClassificationID]) REFERENCES [AVL].[DEBT_MAS_DebtClassificationInfra] ([DebtClassificationID]),
    CONSTRAINT [FK_AnalystResidualID] FOREIGN KEY ([AnalystResidualFlagID]) REFERENCES [AVL].[DEBT_MAS_ResidualDebt] ([ResidualDebtID]),
    CONSTRAINT [FK_AnalystResolutionID] FOREIGN KEY ([AnalystResolutionCodeID]) REFERENCES [AVL].[DEBT_MAP_ResolutionCode] ([ResolutionID]),
    CONSTRAINT [FK_AvoidableID] FOREIGN KEY ([MLAvoidableFlagID]) REFERENCES [AVL].[DEBT_MAS_AvoidableFlag] ([AvoidableFlagID]),
    CONSTRAINT [FK_CauseID] FOREIGN KEY ([MLCauseCodeID]) REFERENCES [AVL].[DEBT_MAP_CauseCode] ([CauseID]),
    CONSTRAINT [FK_ContinuousLearningID] FOREIGN KEY ([ContLearningID]) REFERENCES [ML].[CL_PRJ_InfraContLearningState] ([ContLearningID]),
    CONSTRAINT [FK_DebtClassificationID] FOREIGN KEY ([MLDebtClassificationID]) REFERENCES [AVL].[DEBT_MAS_DebtClassificationInfra] ([DebtClassificationID]),
    CONSTRAINT [FK_InfraPatternValidationProjectID] FOREIGN KEY ([ProjectID]) REFERENCES [AVL].[MAS_ProjectMaster] ([ProjectID]),
    CONSTRAINT [FK_ResidualID] FOREIGN KEY ([MLResidualFlagID]) REFERENCES [AVL].[DEBT_MAS_ResidualDebt] ([ResidualDebtID]),
    CONSTRAINT [FK_ResolutionID] FOREIGN KEY ([MLResolutionCodeID]) REFERENCES [AVL].[DEBT_MAP_ResolutionCode] ([ResolutionID]),
    CONSTRAINT [FK_SMEAvoidableID] FOREIGN KEY ([SMEAvoidableFlagID]) REFERENCES [AVL].[DEBT_MAS_AvoidableFlag] ([AvoidableFlagID]),
    CONSTRAINT [FK_SMECauseID] FOREIGN KEY ([SMECauseCodeID]) REFERENCES [AVL].[DEBT_MAP_CauseCode] ([CauseID]),
    CONSTRAINT [FK_SMEDebtClassificationID] FOREIGN KEY ([SMEDebtClassificationID]) REFERENCES [AVL].[DEBT_MAS_DebtClassificationInfra] ([DebtClassificationID]),
    CONSTRAINT [FK_SMEResidualID] FOREIGN KEY ([SMEResidualFlagID]) REFERENCES [AVL].[DEBT_MAS_ResidualDebt] ([ResidualDebtID])
);

