CREATE TABLE [ML].[InfraTRN_PatternValidation] (
    [ID]                         BIGINT          IDENTITY (1, 1) NOT NULL,
    [InitialLearningID]          BIGINT          NULL,
    [ProjectID]                  BIGINT          NULL,
    [TowerID]                    BIGINT          NULL,
    [TechnologyID]               INT             NULL,
    [TicketPattern]              NVARCHAR (200)  NULL,
    [MLResidualFlagID]           INT             NULL,
    [MLDebtClassificationID]     INT             NULL,
    [MLAvoidableFlagID]          INT             NULL,
    [MLCauseCodeID]              INT             NULL,
    [MLAccuracy]                 DECIMAL (18, 2) NULL,
    [TicketOccurence]            INT             NULL,
    [IsApprovedOrMute]           INT             NULL,
    [ReasonForResidual]          INT             NULL,
    [ExpectedCompDate]           DATETIME        NULL,
    [MLResolutionCode]           INT             NULL,
    [subPattern]                 NVARCHAR (MAX)  DEFAULT ('0') NOT NULL,
    [additionalPattern]          NVARCHAR (MAX)  DEFAULT ('0') NOT NULL,
    [additionalSubPattern]       NVARCHAR (MAX)  DEFAULT ('0') NOT NULL,
    [OverridenPatternCount]      INT             NULL,
    [OverridenPatternTotalCount] INT             NULL,
    [IsMLSignOff]                INT             DEFAULT ((0)) NULL,
    [ContinuousLearningID]       BIGINT          CONSTRAINT [DF_InfraTRN_PatternValidation_ContinuousLearningID] DEFAULT (NULL) NULL,
    [IsDeleted]                  BIT             NULL,
    [CreatedBy]                  NVARCHAR (50)   NULL,
    [CreatedDate]                DATETIME        NULL,
    [ModifiedBy]                 NVARCHAR (50)   NULL,
    [ModifiedDate]               DATETIME        NULL,
    [MLOverriddenId]             INT             NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

