CREATE TABLE [ML].[TicketsforAutoClassification] (
    [ID]                          BIGINT          IDENTITY (1, 1) NOT NULL,
    [BatchProcessId]              BIGINT          NOT NULL,
    [TicketId]                    NVARCHAR (50)   NOT NULL,
    [TicketDescription]           NVARCHAR (MAX)  NULL,
    [AssignmentGroupId]           BIGINT          NULL,
    [Category]                    NVARCHAR (MAX)  NULL,
    [CauseCodeMapID]              BIGINT          NULL,
    [ResolutionCodeMapID]         BIGINT          NULL,
    [AvoidableFlagId]             BIGINT          NULL,
    [ResidualFlagId]              BIGINT          NULL,
    [DebtClassificationId]        BIGINT          NULL,
    [TicketSourceMapID]           BIGINT          NULL,
    [TicketTypeMapID]             BIGINT          NULL,
    [TicketSummary]               NVARCHAR (MAX)  NULL,
    [ResolutionRemarks]           NVARCHAR (MAX)  NULL,
    [Comments]                    NVARCHAR (1000) NULL,
    [FlexField1]                  NVARCHAR (MAX)  NULL,
    [FlexField2]                  NVARCHAR (MAX)  NULL,
    [FlexField3]                  NVARCHAR (MAX)  NULL,
    [FlexField4]                  NVARCHAR (MAX)  NULL,
    [KEDBAvailableIndicatorMapID] BIGINT          NULL,
    [RelatedTickets]              NVARCHAR (50)   NULL,
    [ReleaseTypeMapID]            BIGINT          NULL,
    [SupportType]                 INT             NULL,
    [ApplicationId]               BIGINT          NULL,
    [TowerId]                     BIGINT          NULL,
    [ClusterID_Desc]              INT             NULL,
    [ClusterID_Resolution]        INT             NULL,
    [StatusId]                    BIGINT          NOT NULL,
    [Message]                     NVARCHAR (MAX)  NULL,
    [IsDeleted]                   BIT             NULL,
    [CreatedBy]                   NVARCHAR (50)   NULL,
    [CreatedDate]                 DATETIME        NULL,
    [ModifiedBy]                  NVARCHAR (50)   NULL,
    [ModifiedDate]                DATETIME        NULL,
    [ByMLorDD]                    VARCHAR (10)    NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([StatusId]) REFERENCES [MAS].[MachineLearning] ([ID])
);

