CREATE TABLE [ML].[TRN_MLTransaction] (
    [TransactionId]             BIGINT         IDENTITY (1, 1) NOT NULL,
    [ProjectId]                 BIGINT         NOT NULL,
    [SignOffDate]               DATETIME       NULL,
    [SupportTypeId]             SMALLINT       DEFAULT ((1)) NOT NULL,
    [AlgorithmKey]              NVARCHAR (6)   NOT NULL,
    [ModelAccuracy]             NVARCHAR (50)  NULL,
    [IsActiveTransaction]       BIT            NOT NULL,
    [IssueDefinitionId]         SMALLINT       NULL,
    [ResolutionProviderId]      SMALLINT       NULL,
    [FromDate]                  DATETIME       NULL,
    [ToDate]                    DATETIME       NULL,
    [IsNoiseEnabled]            BIT            NOT NULL,
    [IsDeleted]                 BIT            NULL,
    [CreatedBy]                 NVARCHAR (50)  NOT NULL,
    [CreatedDate]               DATETIME       NOT NULL,
    [ModifiedBy]                NVARCHAR (50)  NULL,
    [ModifiedDate]              DATETIME       NULL,
    [ScreenId]                  SMALLINT       NULL,
    [ErrorPercentage]           NVARCHAR (50)  NULL,
    [DispersionRatioPercentage] NVARCHAR (50)  NULL,
    [JobStatusKey]              NVARCHAR (6)   NULL,
    [JobMessage]                NVARCHAR (MAX) NULL,
    [NoiseStatusKey]            NVARCHAR (12)  NULL,
    [DQVStatusKey]              NVARCHAR (12)  NULL,
    PRIMARY KEY CLUSTERED ([TransactionId] ASC),
    FOREIGN KEY ([IssueDefinitionId]) REFERENCES [MAS].[ML_Prerequisite_FieldMapping] ([FieldMappingId]),
    FOREIGN KEY ([IssueDefinitionId]) REFERENCES [MAS].[ML_Prerequisite_FieldMapping] ([FieldMappingId]),
    FOREIGN KEY ([ScreenId]) REFERENCES [MAS].[MLScreens] ([ScreenId]),
    FOREIGN KEY ([ScreenId]) REFERENCES [MAS].[MLScreens] ([ScreenId])
);

