CREATE TABLE [ML].[TRN_DataQuality_OutCome_App] (
    [DataQualityId]               INT           IDENTITY (1, 1) NOT NULL,
    [MLTransactionId]             BIGINT        NOT NULL,
    [ApplicationId]               BIGINT        NOT NULL,
    [TotalTickets]                INT           NOT NULL,
    [MetricKey]                   NVARCHAR (6)  NOT NULL,
    [IsSelected]                  BIT           NOT NULL,
    [IsTransactionExists]         BIT           NOT NULL,
    [TicketDescriptionCount]      NVARCHAR (50) NULL,
    [DebtClassificationCount]     NVARCHAR (50) NULL,
    [AvoidableFlagCount]          NVARCHAR (50) NULL,
    [ResidualFlagCount]           NVARCHAR (50) NULL,
    [ResolutionRemarksCount]      NVARCHAR (50) NULL,
    [CauseCodeCount]              NVARCHAR (50) NOT NULL,
    [ResolutionCodeCount]         NVARCHAR (50) NOT NULL,
    [RatingKey]                   NVARCHAR (6)  NULL,
    [IsDeleted]                   BIT           NOT NULL,
    [CreatedBy]                   NVARCHAR (50) NOT NULL,
    [CreatedDate]                 DATETIME      NOT NULL,
    [ModifiedBy]                  NVARCHAR (50) NULL,
    [ModifiedDate]                DATETIME      NULL,
    [AssignmentGroupCount]        NVARCHAR (50) NULL,
    [CategoryCount]               NVARCHAR (50) NULL,
    [CommentsCount]               NVARCHAR (50) NULL,
    [FlexField1Count]             NVARCHAR (50) NULL,
    [FlexField2Count]             NVARCHAR (50) NULL,
    [FlexField3Count]             NVARCHAR (50) NULL,
    [FlexField4Count]             NVARCHAR (50) NULL,
    [KEDBAvailableIndicatorCount] NVARCHAR (50) NULL,
    [RelatedTicketsCount]         NVARCHAR (50) NULL,
    [ReleaseTypeCount]            NVARCHAR (50) NULL,
    [TicketsourceCount]           NVARCHAR (50) NULL,
    [TicketSummaryCount]          NVARCHAR (50) NULL,
    [TicketTypeCount]             NVARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([DataQualityId] ASC),
    FOREIGN KEY ([ApplicationId]) REFERENCES [AVL].[APP_MAS_ApplicationDetails] ([ApplicationID]),
    FOREIGN KEY ([ApplicationId]) REFERENCES [AVL].[APP_MAS_ApplicationDetails] ([ApplicationID]),
    FOREIGN KEY ([ApplicationId]) REFERENCES [AVL].[APP_MAS_ApplicationDetails] ([ApplicationID]),
    FOREIGN KEY ([ApplicationId]) REFERENCES [AVL].[APP_MAS_ApplicationDetails] ([ApplicationID]),
    FOREIGN KEY ([MLTransactionId]) REFERENCES [ML].[TRN_MLTransaction] ([TransactionId]),
    FOREIGN KEY ([MLTransactionId]) REFERENCES [ML].[TRN_MLTransaction] ([TransactionId]),
    FOREIGN KEY ([MLTransactionId]) REFERENCES [ML].[TRN_MLTransaction] ([TransactionId])
);

