CREATE TABLE [ML].[TRN_ClusteringTicketValidation_Infra] (
    [ClusteringTicketValidationID] BIGINT         IDENTITY (1, 1) NOT NULL,
    [MLTransactionId]              BIGINT         NOT NULL,
    [ProjectID]                    BIGINT         NOT NULL,
    [TicketID]                     NVARCHAR (50)  NOT NULL,
    [TicketDescription]            NVARCHAR (MAX) NULL,
    [TowerId]                      BIGINT         NOT NULL,
    [DebtClassificationID]         BIGINT         NULL,
    [AvoidableFlagID]              INT            NULL,
    [ResidualDebtID]               BIGINT         NULL,
    [CauseCodeID]                  BIGINT         NULL,
    [ResolutionCodeID]             BIGINT         NULL,
    [DescriptionText]              NVARCHAR (MAX) NULL,
    [IsDeleted]                    BIT            NOT NULL,
    [CreatedBy]                    NVARCHAR (50)  NOT NULL,
    [CreatedDate]                  DATETIME       NOT NULL,
    [ModifiedBy]                   NVARCHAR (50)  NULL,
    [ModifiedDate]                 DATETIME       NULL,
    [ClusterID_Desc]               INT            NULL,
    [Description_threshold]        INT            NULL,
    [modified_description]         NVARCHAR (MAX) NULL,
    [AdditionalText]               NVARCHAR (MAX) NULL,
    [ClusterID_Resolution]         INT            NULL,
    [Resolution_threshold]         INT            NULL,
    [modified_resolution]          NVARCHAR (MAX) NULL,
    [IsOverwrite]                  INT            NULL,
    [IsFreeze]                     BIT            NULL,
    [isSelected]                   BIT            NULL,
    [TicketSummary]                NVARCHAR (MAX) NULL,
    [SummaryText]                  NVARCHAR (MAX) NULL,
    [TicketType]                   VARCHAR (6)    DEFAULT ('LT002') NOT NULL,
    [FromDate]                     DATETIME       NULL,
    [ToDate]                       DATETIME       NULL,
    [Description_Keys_Tokens]      NVARCHAR (MAX) NULL,
    [Resolution_Keys_Tokens]       NVARCHAR (MAX) NULL,
    [CLJobRunDate]                 DATETIME       NULL,
    [CLOutcomeReviewDate]          DATETIME       NULL,
    [IsCLReviewCompleted]          BIT            DEFAULT ((0)) NULL,
    [IsManualClassification]       BIT            NULL,
    [JobName]                      VARCHAR (50)   NULL,
    CONSTRAINT [PK__TRN_Clus__4746F443F2A5D366] PRIMARY KEY CLUSTERED ([ClusteringTicketValidationID] ASC),
    CONSTRAINT [FK__TRN_Clust__MLTra__158C28B8] FOREIGN KEY ([MLTransactionId]) REFERENCES [ML].[TRN_MLTransaction] ([TransactionId]),
    CONSTRAINT [FK__TRN_Clust__Tower__7C8B70C4] FOREIGN KEY ([TowerId]) REFERENCES [AVL].[InfraTowerDetailsTransaction] ([InfraTowerTransactionID])
);

