CREATE TABLE [SA].[TicketMasterNew] (
    [TimeTickerID]                BIGINT          NULL,
    [TicketID]                    NVARCHAR (100)  NULL,
    [ApplicationID]               BIGINT          NULL,
    [ProjectID]                   BIGINT          NULL,
    [AssignedTo]                  NVARCHAR (50)   NULL,
    [AssignmentGroup]             NVARCHAR (50)   NULL,
    [ClientUserID]                NVARCHAR (50)   NULL,
    [EffortTillDate]              DECIMAL (18, 2) NULL,
    [ServiceID]                   INT             NULL,
    [TicketDescription]           NVARCHAR (MAX)  NULL,
    [IsDeleted]                   BIT             NULL,
    [CauseCodeMapID]              BIGINT          NULL,
    [DebtClassificationMapID]     BIGINT          NULL,
    [ResidualDebtMapID]           BIGINT          NULL,
    [ResolutionCodeMapID]         BIGINT          NULL,
    [ResolutionMethodMapID]       BIGINT          NULL,
    [KEDBAvailableIndicatorMapID] BIGINT          NULL,
    [KEDBUpdatedMapID]            BIGINT          NULL,
    [KEDBPath]                    NCHAR (10)      NULL,
    [PriorityMapID]               BIGINT          NULL,
    [ReleaseTypeMapID]            BIGINT          NULL,
    [SeverityMapID]               BIGINT          NULL,
    [TicketSourceMapID]           BIGINT          NULL,
    [TicketStatusMapID]           BIGINT          NULL,
    [TicketTypeMapID]             BIGINT          NULL,
    [BusinessSourceName]          VARCHAR (50)    NULL,
    [Onsite_Offshore]             VARCHAR (50)    NULL,
    [PlannedEffort]               DECIMAL (10, 2) NULL,
    [EstimatedWorkSize]           DECIMAL (10, 2) NULL,
    [ActualEffort]                DECIMAL (10, 2) NULL,
    [ActualWorkSize]              DECIMAL (10, 2) NULL,
    [Resolvedby]                  VARCHAR (50)    NULL,
    [Closedby]                    VARCHAR (50)    NULL,
    [ElevateFlagInternal]         BIT             NULL,
    [RCAID]                       VARCHAR (50)    NULL,
    [PlannedDuration]             DECIMAL (10, 2) NULL,
    [Actualduration]              DECIMAL (10, 2) NULL,
    [TicketSummary]               VARCHAR (100)   NULL,
    [NatureoftheTicket]           VARCHAR (50)    NULL,
    [Comments]                    VARCHAR (50)    NULL,
    [RepeatedIncident]            VARCHAR (50)    NULL,
    [RelatedTickets]              VARCHAR (100)   NULL,
    [TicketCreatedBy]             VARCHAR (50)    NULL,
    [SecondaryResources]          VARCHAR (50)    NULL,
    [EscalatedFlagCustomer]       VARCHAR (50)    NULL,
    [ReasonforRejection]          VARCHAR (100)   NULL,
    [AvoidableFlag]               BIT             NULL,
    [ReleaseDate]                 DATETIME        NULL,
    [TicketCreateDate]            DATETIME        NULL,
    [PlannedStartDate]            DATETIME        NULL,
    [PlannedEndDate]              DATETIME        NULL,
    [ActualStartdateTime]         DATETIME        NULL,
    [ActualEnddateTime]           DATETIME        NULL,
    [OpenDateTime]                DATETIME        NULL,
    [StartedDateTime]             DATETIME        NULL,
    [WIPDateTime]                 DATETIME        NULL,
    [OnHoldDateTime]              DATETIME        NULL,
    [CompletedDateTime]           DATETIME        NULL,
    [ReopenDateTime]              DATETIME        NULL,
    [CancelledDateTime]           DATETIME        NULL,
    [RejectedDateTime]            DATETIME        NULL,
    [Closeddate]                  DATETIME        NULL,
    [AssignedDateTime]            DATETIME        NULL,
    [OutageDuration]              DECIMAL (10, 2) NULL,
    [MetResponseSLAMapID]         INT             NULL,
    [MetAcknowledgementSLAMapID]  INT             NULL,
    [MetResolutionMapID]          INT             NULL,
    [IsTicketApproved]            BIT             NULL,
    [IsManual]                    BIT             NULL,
    [CreatedBy]                   NVARCHAR (50)   NULL,
    [CreatedDate]                 DATETIME        NULL,
    [LastUpdatedDate]             DATETIME        NULL,
    [ModifiedBy]                  NVARCHAR (50)   NULL,
    [ModifiedDate]                DATETIME        NULL
);

