CREATE TYPE [PP].[TVP_OplDataDetails] AS TABLE (
    [ESA_Project_ID]                                            NVARCHAR (MAX) NULL,
    [Merge_Status]                                              NVARCHAR (MAX) NULL,
    [ESA_Project_Name]                                          NVARCHAR (MAX) NULL,
    [Mainspring_Project_ID]                                     NVARCHAR (MAX) NULL,
    [Execution_Project_Name]                                    NVARCHAR (MAX) NULL,
    [Main_Sub_Project_Flag]                                     NVARCHAR (MAX) NULL,
    [Project_Start_Date]                                        DATETIME       NULL,
    [Project_End_Date]                                          DATETIME       NULL,
    [Project_Ported_Date]                                       DATETIME       NULL,
    [Is_mainspring_Ported]                                      NVARCHAR (MAX) NULL,
    [ESA_PM_ID]                                                 NVARCHAR (MAX) NULL,
    [ESA_PM_name]                                               NVARCHAR (MAX) NULL,
    [Project Owner Id]                                          NVARCHAR (MAX) NULL,
    [Project Owner Name]                                        NVARCHAR (MAX) NULL,
    [Project Owner Location]                                    NVARCHAR (MAX) NULL,
    [Project Owner / ESA PM department]                         NVARCHAR (MAX) NULL,
    [Service_line_(LOS)]                                        NVARCHAR (MAX) NULL,
    [Project_Owning_Unit]                                       NVARCHAR (MAX) NULL,
    [Other_Practice_Involved]                                   NVARCHAR (MAX) NULL,
    [No_Practice_Involved]                                      NVARCHAR (MAX) NULL,
    [Client_ID]                                                 NVARCHAR (MAX) NULL,
    [Client_Name]                                               NVARCHAR (MAX) NULL,
    [Parent_Account ID]                                         NVARCHAR (MAX) NULL,
    [Parent_Account]                                            NVARCHAR (MAX) NULL,
    [Account_Segmentation]                                      NVARCHAR (MAX) NULL,
    [Vertical]                                                  NVARCHAR (MAX) NULL,
    [Sub_Vertical]                                              NVARCHAR (MAX) NULL,
    [Primary Market]                                            NVARCHAR (MAX) NULL,
    [Primary Market unit]                                       NVARCHAR (MAX) NULL,
    [Primary BU]                                                NVARCHAR (MAX) NULL,
    [Market]                                                    NVARCHAR (MAX) NULL,
    [Market_Unit]                                               NVARCHAR (MAX) NULL,
    [BU]                                                        NVARCHAR (MAX) NULL,
    [SBU1]                                                      NVARCHAR (MAX) NULL,
    [SBU2]                                                      NVARCHAR (MAX) NULL,
    [ESA_Project_Location]                                      NVARCHAR (MAX) NULL,
    [ESA_Project_City]                                          NVARCHAR (MAX) NULL,
    [ESA_Project_Country]                                       NVARCHAR (MAX) NULL,
    [PL_ID]                                                     NVARCHAR (MAX) NULL,
    [PL_Name]                                                   NVARCHAR (MAX) NULL,
    [Project_Type_Conversion_Date]                              DATETIME       NULL,
    [ESA_Project_Type]                                          NVARCHAR (MAX) NULL,
    [Billability]                                               NVARCHAR (MAX) NULL,
    [ESA_Project_category]                                      NVARCHAR (MAX) NULL,
    [FTE_Offshore]                                              NVARCHAR (MAX) NULL,
    [FTE_Onsite]                                                NVARCHAR (MAX) NULL,
    [Total_FTE]                                                 NVARCHAR (MAX) NULL,
    [Technology]                                                NVARCHAR (MAX) NULL,
    [AD_Qualifier]                                              NVARCHAR (MAX) NULL,
    [Delivery_Eng_Model]                                        NVARCHAR (MAX) NULL,
    [Rhythm]                                                    NVARCHAR (MAX) NULL,
    [Solution_Area]                                             NVARCHAR (MAX) NULL,
    [Sub_Solution_Area]                                         NVARCHAR (MAX) NULL,
    [Solution_type]                                             NVARCHAR (MAX) NULL,
    [Methodologies]                                             NVARCHAR (MAX) NULL,
    [OrgProcessPackageName]                                     NVARCHAR (MAX) NULL,
    [Process_Service_Line]                                      NVARCHAR (MAX) NULL,
    [Capability_Services]                                       NVARCHAR (MAX) NULL,
    [Service_Type]                                              NVARCHAR (MAX) NULL,
    [Language]                                                  NVARCHAR (MAX) NULL,
    [Front_End]                                                 NVARCHAR (MAX) NULL,
    [Back_End]                                                  NVARCHAR (MAX) NULL,
    [Operating_System]                                          NVARCHAR (MAX) NULL,
    [Third_Party_Tools]                                         NVARCHAR (MAX) NULL,
    [Internal_Tools]                                            NVARCHAR (MAX) NULL,
    [Hardware]                                                  NVARCHAR (MAX) NULL,
    [AVMSBUFlag]                                                NVARCHAR (MAX) NULL,
    [MedicalDevice]                                             NVARCHAR (MAX) NULL,
    [DevOpsApplicability]                                       NVARCHAR (MAX) NULL,
    [First_Audit_date_after_KickoffFRS_Excluding_startup]       DATETIME       NULL,
    [Last PreAudit Check_FRS Date]                              DATETIME       NULL,
    [Last_Audit_Date]                                           DATETIME       NULL,
    [Last_Auditor]                                              NVARCHAR (MAX) NULL,
    [Last_Audit_Type]                                           NVARCHAR (MAX) NULL,
    [Opportunity ID]                                            NVARCHAR (MAX) NULL,
    [PursuitCategory]                                           NVARCHAR (MAX) NULL,
    [Final_Scope]                                               NVARCHAR (MAX) NULL,
    [Reason_For_Scope_Change]                                   NVARCHAR (MAX) NULL,
    [TAT(Scoping)]                                              NVARCHAR (MAX) NULL,
    [Final_Category]                                            NVARCHAR (MAX) NULL,
    [Automation_Applicability]                                  NVARCHAR (MAX) NULL,
    [Type_Of_Automation]                                        NVARCHAR (MAX) NULL,
    [Automation_Details]                                        NVARCHAR (MAX) NULL,
    [CDE_-_Data_Restriction]                                    NVARCHAR (MAX) NULL,
    [CDE_-_Client_Tool_Used]                                    NVARCHAR (MAX) NULL,
    [CDE_-_Project_Scope_Involved]                              NVARCHAR (MAX) NULL,
    [CDE_-_Architectural_Considerations]                        NVARCHAR (MAX) NULL,
    [CDE_-_Team_Composition_Consists_Of]                        NVARCHAR (MAX) NULL,
    [CDE_-_Methodology_Followed]                                NVARCHAR (MAX) NULL,
    [CDE_-_CustomerBuildOrDefine]                               NVARCHAR (MAX) NULL,
    [Tracking Mode]                                             NVARCHAR (MAX) NULL,
    [Is Performance data sharing is restricted as per contract] NVARCHAR (MAX) NULL,
    [3x3 Matrix]                                                NVARCHAR (MAX) NULL);

