CREATE TABLE [dbo].['AVM Project List - 08th March$'] (
    [project_id]                             FLOAT (53)     NULL,
    [project_name]                           NVARCHAR (255) NULL,
    [project_start_date]                     DATETIME       NULL,
    [project_end_date]                       DATETIME       NULL,
    [project_type]                           NVARCHAR (255) NULL,
    [bill_type]                              NVARCHAR (255) NULL,
    [solution_type_code]                     NVARCHAR (255) NULL,
    [Project_Category]                       NVARCHAR (255) NULL,
    [cts_vertical]                           NVARCHAR (255) NULL,
    [projectowningpractice]                  NVARCHAR (255) NULL,
    [OWNING BU]                              NVARCHAR (255) NULL,
    [AVM FTE]                                FLOAT (53)     NULL,
    [Total FTE]                              FLOAT (53)     NULL,
    [customer_id]                            FLOAT (53)     NULL,
    [accountname]                            NVARCHAR (255) NULL,
    [parentcustomerid]                       FLOAT (53)     NULL,
    [ParentCustomerName]                     NVARCHAR (255) NULL,
    [bu_id]                                  FLOAT (53)     NULL,
    [SBU Name]                               NVARCHAR (255) NULL,
    [sbu1name]                               NVARCHAR (255) NULL,
    [sbu2name]                               NVARCHAR (255) NULL,
    [project_manager]                        FLOAT (53)     NULL,
    [project_manager_nm]                     NVARCHAR (255) NULL,
    [pm_dept_id]                             NVARCHAR (255) NULL,
    [pm_dept_nm]                             NVARCHAR (255) NULL,
    [deliverymanagerid]                      FLOAT (53)     NULL,
    [deliverymanager_nm]                     NVARCHAR (255) NULL,
    [deliverymanager_dept_id]                NVARCHAR (255) NULL,
    [deliverymanager_dept_nm]                NVARCHAR (255) NULL,
    [project_owner]                          FLOAT (53)     NULL,
    [project_owner_nm]                       NVARCHAR (255) NULL,
    [project_owner_dept_id]                  NVARCHAR (255) NULL,
    [project_owner_dept_nm]                  NVARCHAR (255) NULL,
    [DE Scope _(As in OPL)]                  NVARCHAR (255) NULL,
    [Updated DE Scope for Applens Exclusion] NVARCHAR (255) NULL,
    [Part of Exclusion List?]                NVARCHAR (255) NULL,
    [In Applens Onboarding List?]            NVARCHAR (255) NULL,
    [MAS only Project ?]                     NVARCHAR (255) NULL
);

