CREATE TABLE [dbo].[DataQualityReport_AssociateLevel_previousmonths] (
    [ID]                                                   INT             IDENTITY (1, 1) NOT NULL,
    [Month]                                                NVARCHAR (12)   NULL,
    [Data_Period]                                          NVARCHAR (50)   NULL,
    [ESA_Project_ID]                                       NVARCHAR (100)  NULL,
    [ESA_Project_Name]                                     NVARCHAR (200)  NULL,
    [AssociateID]                                          NVARCHAR (100)  NULL,
    [Associate Name]                                       NVARCHAR (200)  NULL,
    [ESA_PM_NAME]                                          NVARCHAR (250)  NULL,
    [ESA_PM_ID]                                            NVARCHAR (10)   NULL,
    [Archetype_Cluster]                                    NVARCHAR (100)  NULL,
    [Archetype]                                            NVARCHAR (100)  NULL,
    [Work_Category]                                        NVARCHAR (1000) NULL,
    [Parent_Account]                                       NVARCHAR (250)  NULL,
    [Practice_Area_PBI]                                    NVARCHAR (100)  NULL,
    [Project_Owning_Unit]                                  NVARCHAR (250)  NULL,
    [Market]                                               NVARCHAR (200)  NULL,
    [Market_Unit]                                          NVARCHAR (200)  NULL,
    [Project_Owner_Name]                                   NVARCHAR (200)  NULL,
    [Project_Owner_Id]                                     NVARCHAR (50)   NULL,
    [Final_Scope]                                          NVARCHAR (100)  NULL,
    [Total_FTE]                                            FLOAT (53)      NULL,
    [_3x3_Matrix]                                          NVARCHAR (100)  NULL,
    [Project_Type]                                         NVARCHAR (100)  NULL,
    [Avgtktprod]                                           TINYINT         NULL,
    [Avg_Ticket_Productivity_2023_benchmark]               TINYINT         NULL,
    [Status]                                               NVARCHAR (35)   NULL,
    [Total_MPS_Effort_From_Applens]                        DECIMAL (10, 2) NULL,
    [Known_Error_Resolution_Service_Effort]                DECIMAL (7, 2)  NULL,
    [Application_Problem_Management_Service_Effort]        DECIMAL (7, 2)  NULL,
    [Incident_Resolution_Unknown_Services_Effort]          DECIMAL (7, 2)  NULL,
    [Standard_Service_Request_Fulfillment_Effort]          DECIMAL (7, 2)  NULL,
    [Adhoc_Service_Request_Fulfillment_Effort]             DECIMAL (7, 2)  NULL,
    [Operational_Change_Management_Services_Effort]        DECIMAL (7, 2)  NULL,
    [Problem_Management_Activity]                          DECIMAL (7, 2)  NULL,
    [Incident_Management_Activity]                         DECIMAL (7, 2)  NULL,
    [Service_Request_Management_Activity]                  DECIMAL (7, 2)  NULL,
    [Org_Change_Management_Activity]                       DECIMAL (7, 2)  NULL,
    [Change_Release_Management_Activity]                   DECIMAL (7, 2)  NULL,
    [Total_MPS_Effort_From_ESA]                            DECIMAL (7, 2)  NULL,
    [Effort_Deviation]                                     NVARCHAR (250)  NULL,
    [Applens_Volume]                                       DECIMAL (10, 2) NULL,
    [ApplensVolume_Adhoc_Service_Request_Fulfillment]      DECIMAL (7, 2)  NULL,
    [ApplensVolume_Application_Problem_Management_Service] DECIMAL (7, 2)  NULL,
    [ApplensVolume_Incident_Resolution_Unknown_Services]   DECIMAL (7, 2)  NULL,
    [ApplensVolume_Known_Error_Resolution_Service]         DECIMAL (7, 2)  NULL,
    [ApplensVolume_Standard_Service_Request_Fulfillment]   DECIMAL (7, 2)  NULL,
    [ApplensVolume_Operational_Change_Management_Services] DECIMAL (7, 2)  NULL,
    [Expected_Volume]                                      DECIMAL (7, 2)  NULL,
    [Volume_Deviation]                                     DECIMAL (7, 2)  NULL,
    [Tickets_with_ZeroEffort]                              DECIMAL (7, 2)  NULL,
    [Ageing_Tickets]                                       DECIMAL (7, 2)  NULL,
    [Unknown_Incidents_greater_than_100Hours]              DECIMAL (7, 2)  NULL,
    [KnownIncidents_greaterthan_50Hours]                   DECIMAL (7, 2)  NULL,
    [UNKnownIncidents_lessthan_HalfHours]                  DECIMAL (7, 2)  NULL,
    [Ismo_Associate_Timesheet]                             DECIMAL (7, 2)  NULL,
    [Total_Applens_Effort]                                 DECIMAL (10, 2) NULL,
    [Total_ESA_Effort]                                     DECIMAL (10, 2) NULL,
    [CreatedDate]                                          DATETIME        NULL,
    [CreatedBy]                                            NVARCHAR (100)  NULL,
    [Dept_Name]                                            NVARCHAR (30)   NULL,
    [Designation]                                          NVARCHAR (200)  NULL,
    [Grade]                                                CHAR (3)        NULL
);

