CREATE TABLE [dbo].[DataQualityReports_lastrun] (
    [Month]                                   NVARCHAR (MAX)  NULL,
    [ESA_Project_ID]                          NVARCHAR (250)  NULL,
    [ESA_Project_Name]                        NVARCHAR (250)  NULL,
    [Mainspring_Project_ID]                   NVARCHAR (250)  NULL,
    [Execution_Project_Name]                  NVARCHAR (250)  NULL,
    [ESA_PM_NAME]                             NVARCHAR (250)  NULL,
    [ESA_PM_ID]                               NVARCHAR (250)  NULL,
    [Archetype_Cluster]                       NVARCHAR (250)  NULL,
    [Archetype]                               NVARCHAR (250)  NULL,
    [Work_Category]                           NVARCHAR (250)  NULL,
    [Parent_Account]                          NVARCHAR (250)  NULL,
    [Practice_Area_PBI]                       NVARCHAR (250)  NULL,
    [Project_Owning_Unit]                     NVARCHAR (250)  NULL,
    [Industry_Segment]                        NVARCHAR (250)  NULL,
    [Vertical]                                NVARCHAR (250)  NULL,
    [Market]                                  NVARCHAR (250)  NULL,
    [Market_Unit]                             NVARCHAR (250)  NULL,
    [Updated_BU]                              NVARCHAR (250)  NULL,
    [Updated_SBU]                             NVARCHAR (250)  NULL,
    [ESA_Project_Country]                     NVARCHAR (250)  NULL,
    [Project_Owner_ESA_PM_department]         NVARCHAR (250)  NULL,
    [Project_Owner_Name]                      NVARCHAR (250)  NULL,
    [Project_Owner_Id]                        NVARCHAR (250)  NULL,
    [Delivery_Excellence_POC]                 NVARCHAR (250)  NULL,
    [Final_Scope]                             NVARCHAR (250)  NULL,
    [Total_FTE]                               FLOAT (53)      NULL,
    [_3x3_Matrix]                             NVARCHAR (250)  NULL,
    [Project_Type]                            NVARCHAR (250)  NULL,
    [Avgtktprod]                              TINYINT         NULL,
    [Status]                                  NVARCHAR (250)  NULL,
    [Total_MPS_Effort_From_Applens]           DECIMAL (12, 2) NULL,
    [Total_MPS_Effort_From_ESA]               DECIMAL (12, 2) NULL,
    [Total_Applens_Effort]                    DECIMAL (10, 2) NULL,
    [Total_ESA_Effort]                        DECIMAL (10, 2) NULL,
    [Effort_Deviation]                        DECIMAL (10, 2) NULL,
    [Volume]                                  DECIMAL (10, 2) NULL,
    [Expected_Volume]                         DECIMAL (10, 2) NULL,
    [Volume_Deviation]                        DECIMAL (10, 2) NULL,
    [Total_TicketVolume]                      DECIMAL (10, 2) NULL,
    [Tickets_with_ZeroEffort]                 DECIMAL (10, 2) NULL,
    [Ageing_Tickets]                          DECIMAL (10, 2) NULL,
    [Unknown_Incidents_greater_than_100Hours] DECIMAL (10, 2) NULL,
    [KnownIncidents_greaterthan_50Hours]      DECIMAL (10, 2) NULL,
    [UNKnownIncidents_lessthan_HalfHours]     DECIMAL (10, 2) NULL,
    [Ismo_Associate_Timesheet]                DECIMAL (10, 2) NULL,
    [Differencess]                            DECIMAL (10, 2) NULL,
    [CreatedDate]                             DATETIME        NULL,
    [CreatedBy]                               NVARCHAR (50)   NULL
);

