CREATE TABLE [dbo].[DebtReviewTemp] (
    [ID]                      INT            IDENTITY (1, 1) NOT NULL,
    [TicketID]                NVARCHAR (100) NULL,
    [Application Name]        NVARCHAR (100) NULL,
    [Service Name]            NVARCHAR (100) NULL,
    [Assignee]                NVARCHAR (50)  NULL,
    [Cause Code]              NVARCHAR (100) NULL,
    [CauseCodeMapID]          BIGINT         NULL,
    [Resolution Code]         NVARCHAR (100) NULL,
    [ResolutionCodeMapID]     BIGINT         NULL,
    [Debt Category]           NVARCHAR (100) NULL,
    [DebtClassificationMapID] BIGINT         NULL,
    [Avoidable Flag]          NVARCHAR (100) NULL,
    [AvoidableFlagID]         INT            NULL,
    [Residual Debt]           NVARCHAR (100) NULL,
    [ResidualDebtMapID]       BIGINT         NULL,
    [Ticket Type]             NVARCHAR (100) NULL,
    [Nature Of The Ticket]    NVARCHAR (100) NULL,
    [NatureoftheTicket]       INT            NULL,
    [KEDB Path]               NVARCHAR (500) NULL,
    [ProjectID]               BIGINT         NULL,
    [IsCognizant]             INT            NULL,
    [FlexField1]              NVARCHAR (MAX) CONSTRAINT [DF_DebtReviewTemp_FlexField1] DEFAULT (NULL) NULL,
    [FlexField2]              NVARCHAR (MAX) CONSTRAINT [DF_DebtReviewTemp_FlexField2] DEFAULT (NULL) NULL,
    [FlexField3]              NVARCHAR (MAX) CONSTRAINT [DF_DebtReviewTemp_FlexField3] DEFAULT (NULL) NULL,
    [FlexField4]              NVARCHAR (MAX) CONSTRAINT [DF_DebtReviewTemp_FlexField4] DEFAULT (NULL) NULL,
    [IsFlexField1Modified]    VARCHAR (20)   NULL,
    [IsFlexField2Modified]    VARCHAR (20)   NULL,
    [IsFlexField3Modified]    VARCHAR (20)   NULL,
    [IsFlexField4Modified]    VARCHAR (20)   NULL,
    [TicketDescription]       NVARCHAR (MAX) NULL
);

