CREATE TABLE [dbo].[detailed_timesheet_Correction] (
    [Project ID]              NVARCHAR (500) NULL,
    [Project]                 NVARCHAR (500) NULL,
    [Ticket ID]               NVARCHAR (500) NULL,
    [Application]             NVARCHAR (500) NULL,
    [Service]                 NVARCHAR (500) NULL,
    [Service Level]           NVARCHAR (500) NULL,
    [Activity]                NVARCHAR (500) NULL,
    [Ticket Type]             NVARCHAR (500) NULL,
    [AppLens Ticket Type]     NVARCHAR (500) NULL,
    [Priority]                NVARCHAR (500) NULL,
    [Hours]                   NVARCHAR (500) NULL,
    [Associate ID]            NVARCHAR (500) NULL,
    [Associate Name]          NVARCHAR (500) NULL,
    [Grade]                   NVARCHAR (500) NULL,
    [Designation]             NVARCHAR (500) NULL,
    [External Login ID]       NVARCHAR (500) NULL,
    [Timesheet Date]          NVARCHAR (500) NULL,
    [Timesheet Status]        NVARCHAR (500) NULL,
    [Assignment Group]        NVARCHAR (500) NULL,
    [LoB]                     NVARCHAR (500) NULL,
    [Portfolio]               NVARCHAR (500) NULL,
    [AppGroup]                NVARCHAR (500) NULL,
    [Application Code]        NVARCHAR (500) NULL,
    [Remarks]                 NVARCHAR (500) NULL,
    [Timesheet Approver ID]   NVARCHAR (500) NULL,
    [Timesheet Approver Name] NVARCHAR (500) NULL,
    [Tower]                   NVARCHAR (500) NULL,
    [Task]                    NVARCHAR (500) NULL,
    [WorkItem ID]             NVARCHAR (500) NULL,
    [WorkItem Details ID]     NVARCHAR (500) NULL,
    [ExecuteStatus]           NVARCHAR (500) NULL,
    [BatchNo]                 NVARCHAR (100) NULL,
    [ApplicationID]           BIGINT         NULL,
    [TimeTickerID]            BIGINT         NULL,
    [timesheetid]             NVARCHAR (100) NULL
);

