CREATE TABLE [dbo].[Final_Data_Daily_DEleads_Test] (
    [Account ID]                  CHAR (15)       NULL,
    [Account Name]                VARCHAR (60)    NULL,
    [Project ID]                  CHAR (15)       NOT NULL,
    [Project Name]                VARCHAR (274)   NULL,
    [SDM ID]                      NVARCHAR (MAX)  NULL,
    [SDM Name]                    NVARCHAR (MAX)  NULL,
    [Project Owning Practice]     NVARCHAR (50)   NULL,
    [Practice Owner]              NVARCHAR (50)   NULL,
    [SDD ID]                      NVARCHAR (MAX)  NULL,
    [SDD Name]                    NVARCHAR (MAX)  NULL,
    [ESA FTE Count M and Above]   DECIMAL (10, 2) NULL,
    [Available Hours M and Above] DECIMAL (10, 2) NULL,
    [AVM Dart Hours Ticketed]     DECIMAL (10, 2) NULL,
    [AVM Dart Hours NonTicketed]  DECIMAL (10, 2) NULL,
    [AVM Dart Hours]              DECIMAL (10, 2) NULL,
    [ESA FTE Count Below M]       DECIMAL (10, 2) NULL,
    [Available Hours Below M]     DECIMAL (10, 2) NULL,
    [MAS Effort]                  DECIMAL (10, 2) NULL,
    [Ticketed Effort]             DECIMAL (10, 2) NULL,
    [NonTicketed Effort]          DECIMAL (10, 2) NULL,
    [Total AVM Effort]            DECIMAL (10, 2) NULL,
    [MAS MPS Effort_Hours]        VARCHAR (30)    NULL,
    [Onsite MAS_MPS_Hours]        DECIMAL (10, 2) NULL,
    [Offshore MAS_MPS_Hours]      DECIMAL (10, 2) NULL,
    [Percent Ticketed Effort]     DECIMAL (10, 2) NULL,
    [Percent NonTicketed Effort]  DECIMAL (10, 2) NULL,
    [percent TS Compliance]       DECIMAL (10, 2) NULL,
    [Greater Ten]                 BIT             NULL,
    [Greater Eighty]              BIT             NULL
);

