CREATE TABLE [dbo].[OPLMasterdata] (
    [ESA_Project_ID]                                         NVARCHAR (50)   NULL,
    [Merge_Status]                                           NVARCHAR (3000) NULL,
    [ESA_Project_Name]                                       NVARCHAR (3000) NULL,
    [Mainspring_Project_ID]                                  NVARCHAR (50)   NULL,
    [Execution_Project_Name]                                 NVARCHAR (3000) NULL,
    [Main_Sub_Project_Flag]                                  NVARCHAR (3000) NULL,
    [Project_Start_Date]                                     DATETIME        NULL,
    [Project_End_Date]                                       DATETIME        NULL,
    [Project_Ported_Date]                                    DATETIME        NULL,
    [Is_mainspring_Ported]                                   NVARCHAR (3000) NULL,
    [ESA_PM_ID]                                              NVARCHAR (100)  NULL,
    [ESA_PM_name]                                            NVARCHAR (3000) NULL,
    [Project Owner Id]                                       NVARCHAR (100)  NULL,
    [Project Owner Name]                                     NVARCHAR (3000) NULL,
    [Project Owner Location]                                 NVARCHAR (3000) NULL,
    [Project Owner / ESA PM department]                      NVARCHAR (3000) NULL,
    [Service_line_(LOS)]                                     NVARCHAR (3000) NULL,
    [Project_Owning_Unit]                                    NVARCHAR (3000) NULL,
    [Other_Practice_Involved]                                NVARCHAR (3000) NULL,
    [No_Practice_Involved]                                   NVARCHAR (3000) NULL,
    [Client_ID]                                              NVARCHAR (100)  NULL,
    [Client_Name]                                            NVARCHAR (3000) NULL,
    [Parent_Account ID]                                      NVARCHAR (100)  NULL,
    [Parent_Account]                                         NVARCHAR (3000) NULL,
    [Account_Segmentation]                                   NVARCHAR (3000) NULL,
    [Vertical]                                               NVARCHAR (3000) NULL,
    [Sub_Vertical]                                           NVARCHAR (3000) NULL,
    [Primary Market]                                         NVARCHAR (3000) NULL,
    [Primary Market unit]                                    NVARCHAR (3000) NULL,
    [Primary BU]                                             NVARCHAR (3000) NULL,
    [Market]                                                 NVARCHAR (3000) NULL,
    [Market_Unit]                                            NVARCHAR (3000) NULL,
    [BU]                                                     NVARCHAR (3000) NULL,
    [SBU1]                                                   NVARCHAR (3000) NULL,
    [SBU2]                                                   NVARCHAR (3000) NULL,
    [ESA_Project_Location]                                   NVARCHAR (3000) NULL,
    [ESA_Project_City]                                       NVARCHAR (3000) NULL,
    [ESA_Project_Country]                                    NVARCHAR (3000) NULL,
    [PL_ID]                                                  NVARCHAR (150)  NULL,
    [PL_Name]                                                NVARCHAR (3000) NULL,
    [Project_Type_Conversion_Date]                           DATETIME        NULL,
    [ESA_Project_Type]                                       NVARCHAR (3000) NULL,
    [Billability]                                            NVARCHAR (3000) NULL,
    [ESA_Project_category]                                   NVARCHAR (3000) NULL,
    [FTE_Offshore]                                           NVARCHAR (100)  NULL,
    [FTE_Onsite]                                             NVARCHAR (100)  NULL,
    [Total_FTE]                                              NVARCHAR (100)  NULL,
    [Technology]                                             NVARCHAR (4000) NULL,
    [AD_Qualifier]                                           NVARCHAR (3000) NULL,
    [Delivery_Eng_Model]                                     NVARCHAR (3000) NULL,
    [Rhythm]                                                 NVARCHAR (3000) NULL,
    [Solution_Area]                                          NVARCHAR (3000) NULL,
    [Sub_Solution_Area]                                      NVARCHAR (3000) NULL,
    [Solution_type]                                          NVARCHAR (3000) NULL,
    [Methodologies]                                          NVARCHAR (3000) NULL,
    [OrgProcessPackageName]                                  NVARCHAR (3000) NULL,
    [Process_Service_Line]                                   NVARCHAR (3000) NULL,
    [Capability_Services]                                    NVARCHAR (3000) NULL,
    [Service_Type]                                           NVARCHAR (3000) NULL,
    [Language]                                               NVARCHAR (3000) NULL,
    [Front_End]                                              NVARCHAR (3000) NULL,
    [Back_End]                                               NVARCHAR (3000) NULL,
    [Operating_System]                                       NVARCHAR (3000) NULL,
    [Third_Party_Tools]                                      NVARCHAR (3000) NULL,
    [Internal_Tools]                                         NVARCHAR (3000) NULL,
    [Hardware]                                               NVARCHAR (3000) NULL,
    [AVMSBUFlag]                                             NVARCHAR (3000) NULL,
    [MedicalDevice]                                          NVARCHAR (3000) NULL,
    [DevOpsApplicability]                                    NVARCHAR (3000) NULL,
    [First_Audit_date_after_KickoffFRS_Excluding_startup]    DATETIME        NULL,
    [Last PreAudit Check_FRS Date]                           DATETIME        NULL,
    [Last_Audit_Date]                                        DATETIME        NULL,
    [Last_Auditor]                                           NVARCHAR (3000) NULL,
    [Last_Audit_Type]                                        NVARCHAR (3000) NULL,
    [Opportunity ID]                                         NVARCHAR (100)  NULL,
    [PursuitCategory]                                        NVARCHAR (3000) NULL,
    [Final_Scope]                                            NVARCHAR (3000) NULL,
    [Reason_For_Scope_Change]                                NVARCHAR (3000) NULL,
    [TAT(Scoping)]                                           NVARCHAR (3000) NULL,
    [Final_Category]                                         NVARCHAR (3000) NULL,
    [Automation_Applicability]                               NVARCHAR (3000) NULL,
    [Type_Of_Automation]                                     NVARCHAR (3000) NULL,
    [Automation_Details]                                     NVARCHAR (3000) NULL,
    [CDE_-_Data_Restriction]                                 NVARCHAR (3000) NULL,
    [CDE_-_Client_Tool_Used]                                 NVARCHAR (3000) NULL,
    [CDE_-_Project_Scope_Involved]                           NVARCHAR (3000) NULL,
    [CDE_-_Architectural_Considerations]                     NVARCHAR (3000) NULL,
    [CDE_-_Team_Composition_Consists_Of]                     NVARCHAR (3000) NULL,
    [CDE_-_Methodology_Followed]                             NVARCHAR (3000) NULL,
    [CDE_-_CustomerBuildOrDefine]                            NVARCHAR (3000) NULL,
    [IsDeleted]                                              BIT             NOT NULL,
    [CreatedBy]                                              NVARCHAR (50)   NOT NULL,
    [CreatedDate]                                            DATETIME        NOT NULL,
    [ModifiedBy]                                             NVARCHAR (50)   NULL,
    [ModifiedDate]                                           DATETIME        NULL,
    [Tracking Mode]                                          NVARCHAR (100)  NULL,
    [Is Performance data Sharing restricted as per contract] NVARCHAR (100)  NULL,
    [3x3 Matrix]                                             VARCHAR (100)   NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_OPL]
    ON [dbo].[OPLMasterdata]([ESA_Project_ID] ASC);

