CREATE TABLE [dbo].[Service_Analytics_CloseFinal] (
    [Project ID]            NVARCHAR (500) NULL,
    [Project]               NVARCHAR (500) NULL,
    [Application]           NVARCHAR (500) NULL,
    [Tower]                 NVARCHAR (500) NULL,
    [Ticket ID]             NVARCHAR (500) NULL,
    [TicketType]            NVARCHAR (500) NULL,
    [Service]               NVARCHAR (500) NULL,
    [Priority]              NVARCHAR (500) NULL,
    [AppLens Priority]      NVARCHAR (500) NULL,
    [Assignment Group]      NVARCHAR (500) NULL,
    [Ticket Open Date]      NVARCHAR (500) NULL,
    [Aging (Days)]          NVARCHAR (500) NULL,
    [Ticket Closed Date]    NVARCHAR (500) NULL,
    [Effort]                NVARCHAR (500) NULL,
    [Status]                NVARCHAR (500) NULL,
    [Is Manual]             NVARCHAR (500) NULL,
    [Assignee ID]           NVARCHAR (500) NULL,
    [Assigned To]           NVARCHAR (500) NULL,
    [External LoginID]      NVARCHAR (500) NULL,
    [Is SLA Met]            NVARCHAR (500) NULL,
    [ServiceLevelName]      NVARCHAR (500) NULL,
    [Cause Code]            NVARCHAR (500) NULL,
    [Resolution Code]       NVARCHAR (500) NULL,
    [LoB]                   NVARCHAR (500) NULL,
    [Portfolio]             NVARCHAR (500) NULL,
    [AppGroup]              NVARCHAR (500) NULL,
    [Is PartiallyAutomated] NVARCHAR (500) NULL,
    [Is MachineResolved]    NVARCHAR (500) NULL,
    [ExecuteStatus]         NVARCHAR (500) NULL,
    [BatchNo]               NVARCHAR (100) NULL,
    [Applicationid]         BIGINT         NULL,
    [serviceid]             BIGINT         NULL,
    [causeid]               BIGINT         NULL,
    [resolutionid]          BIGINT         NULL,
    [priorityid]            BIGINT         NULL,
    [assignmentgroupid]     BIGINT         NULL,
    [severityid]            BIGINT         NULL,
    [ticketstatusid]        BIGINT         NULL,
    [dartstatusid]          BIGINT         NULL,
    [tickettypemapid]       BIGINT         NULL,
    [project_id]            BIGINT         NULL
);

