/***************************************************************************
*COGNIZANT CONFIDENTIAL AND/OR TRADE SECRET
*Copyright [2018] � [2021] Cognizant. All rights reserved.
*NOTICE: This unpublished material is proprietary to Cognizant and
*its suppliers, if any. The methods, techniques and technical
  concepts herein are considered Cognizant confidential and/or trade secret information. 
  
*This material may be covered by U.S. and/or foreign patents or patent applications. 
*Use, distribution or copying, in whole or in part, is forbidden, except by express written permission of Cognizant.
***************************************************************************/

CREATE   PROCEDURE [dbo].[GetCentralRepository_SFDC_Account]
AS
TRUNCATE TABLE [dbo].[vw_CentralRepository_SFDC_Account]
INSERT INTO [dbo].[vw_CentralRepository_SFDC_Account]
(
	   [Id]
      --,[Createdbyid]
      --,[Createddate]
      --,[Receiveddatetime]
      --,[Lastmodifiedbyid]
      --,[Trackingid]
      ,[Name]
      --,[Duns_Number__C]
      --,[Alternate_Customer_Name__C]
      --,[Account_Owner_Email__C]
      --,[Peoplesoft_Parent_Account_Id__C]
      ,[Customer_Category__C]
      --,[Website]
      --,[Stock_Symbol__C]
      --,[Ao2__Add_To_Cs__C]
      ,[Global_Market__C]
      ,[Vertical__C]
      --,[Sub_Vertical__C]
      --,[Bu__C]
      --,[Sbu_1__C]
      --,[Sbu_2__C]
      --,[Customer__C]
      --,[Partner__C]
      --,[Intermediary1__C]
      --,[Competitor__C]
      --,[Shippingstreet]
      --,[Location_Type__C]
      --,[Shippingcity]
      --,[Shippingstate]
      --,[Shippingcountry]
      --,[Shippingpostalcode]
      --,[Entity_For_Raising_Invoice__C]
      --,[Gl_Bu_Id__C]
      ,[Crm_Status__C]
      --,[Customer_Record_Owned_By__C]
      --,[Ultimate_Parent_Customerid__C]
      ,[Financial_Ultimate_Customer_Id__C]
      --,[Type]
      --,[Sub_Cust_Type__C]
      --,[Tax_Payer_Id__C]
      --,[Region__C]
      ,[Peoplesoft_Customer_Id__C]
      --,[Account_Start_Date__C]
      --,[Account_End_Date__C]
      --,[Partner_Classification__C]
      --,[Acquired_Company__C]
      --,[Internal_Customer__C]
      --,[Qualified__C]
      ,[LastUpdatedDateTime]
      --,[Client_Partner_Id__c]
      --,[Shipping_Street2__c]
      --,[Shipping_Street3__c]
      --,[Shipping_Street4__c]
      --,[BU_Id__c]
      --,[CP_Employee_Number__c]
      ,[Global_Market_Id__c]
      ,[SBU1_Id__c]
      ,[SBU2_Id__c]
      ,[VerticalID__c]
      ,[Sub_Vertical_Id__c]
      ,[RHMS_Vertical_Id__c]
     --,[Country_Id__c]
      --,[State_Id__c]
      --,[Market__c]
      --,[Market_Id__c]
)
SELECT [Id]      
      --,[Createdbyid]
      --,[Createddate]
      --,[Receiveddatetime]
      --,[Lastmodifiedbyid]
      --,[Trackingid]
      ,[Name]
      --,[Duns_Number__C]
      --,[Alternate_Customer_Name__C]
      --,[Account_Owner_Email__C]
      --,[Peoplesoft_Parent_Account_Id__C]
      ,[Customer_Category__C]
      --,[Website]
      --,[Stock_Symbol__C]
      --,[Ao2__Add_To_Cs__C]
      ,[Global_Market__C]
      ,[Vertical__C]
      --,[Sub_Vertical__C]
      --,[Bu__C]
      --,[Sbu_1__C]
      --,[Sbu_2__C]
      --,[Customer__C]
      --,[Partner__C]
      --,[Intermediary1__C]
      --,[Competitor__C]
      --,[Shippingstreet]
      --,[Location_Type__C]
      --,[Shippingcity]
      --,[Shippingstate]
      --,[Shippingcountry]
      --,[Shippingpostalcode]
      --,[Entity_For_Raising_Invoice__C]
      --,[Gl_Bu_Id__C]
      ,[Crm_Status__C]
      --,[Customer_Record_Owned_By__C]
      --,[Ultimate_Parent_Customerid__C]
      ,[Financial_Ultimate_Customer_Id__C]
      --,[Type]
      --,[Sub_Cust_Type__C]
      --,[Tax_Payer_Id__C]
      --,[Region__C]
      ,[Peoplesoft_Customer_Id__C]
      --,[Account_Start_Date__C]
      --,[Account_End_Date__C]
      --,[Partner_Classification__C]
      --,[Acquired_Company__C]
      --,[Internal_Customer__C]
      --,[Qualified__C]
      ,[LastUpdatedDateTime]
      --,[Client_Partner_Id__c]
      --,[Shipping_Street2__c]
      --,[Shipping_Street3__c]
      --,[Shipping_Street4__c]
      --,[BU_Id__c]
      --,[CP_Employee_Number__c]
      ,[Global_Market_Id__c]
      ,[SBU1_Id__c]
      ,[SBU2_Id__c]
      ,[VerticalID__c]
      ,[Sub_Vertical_Id__c]
      ,[RHMS_Vertical_Id__c]
     --,[Country_Id__c]
      --,[State_Id__c]
      --,[Market__c]
      --,[Market_Id__c]
  FROM [$(AVMCOEESADB)].[DBO].[vw_CentralRepository_SFDC_Account] AS tb WITH (NOLOCK);
  
