CREATE TYPE [dbo].[TVP_AdoptionADMProjectDetails] AS TABLE (
    [ESAProjectID]                    NVARCHAR (100) NOT NULL,
    [ESAProjectName]                  NVARCHAR (100) NOT NULL,
    [Project Start Date]              NVARCHAR (50)  NULL,
    [Project End Date]                NVARCHAR (50)  NULL,
    [AccountId]                       NVARCHAR (100) NOT NULL,
    [AccountName]                     NVARCHAR (100) NOT NULL,
    [ParentAccountID]                 NVARCHAR (100) NOT NULL,
    [ParentAccountName]               NVARCHAR (100) NOT NULL,
    [ProjectOwningUnit]               NVARCHAR (50)  NULL,
    [TotalFTE]                        NVARCHAR (50)  NULL,
    [Vertical]                        NVARCHAR (50)  NULL,
    [Market]                          NVARCHAR (50)  NULL,
    [MarketUnit]                      NVARCHAR (50)  NULL,
    [BU]                              NVARCHAR (50)  NULL,
    [SBU1Id]                          NVARCHAR (50)  NULL,
    [SBU1]                            NVARCHAR (50)  NULL,
    [SBU2Id]                          NVARCHAR (50)  NULL,
    [SBU2]                            NVARCHAR (50)  NULL,
    [ESA Project Type]                NVARCHAR (50)  NULL,
    [ESA Project Category]            NVARCHAR (50)  NULL,
    [3x3 Matrix]                      NVARCHAR (50)  NULL,
    [Archetype]                       NVARCHAR (50)  NULL,
    [ArchetypeCluster]                NVARCHAR (50)  NULL,
    [WorkCategory]                    NVARCHAR (500) NULL,
    [PracticeArea]                    NVARCHAR (50)  NULL,
    [IndustrySegment]                 NVARCHAR (50)  NULL,
    [FinalScope]                      NVARCHAR (50)  NULL,
    [DEx Assessment feasibility flag] NVARCHAR (50)  NULL,
    [IsPerformanceSharingRestricted]  NVARCHAR (50)  NULL,
    [FirstInscopeDate]                NVARCHAR (50)  NULL,
    [ESAProjectCountry]               NVARCHAR (50)  NULL,
    [ESA_PM_Id]                       NVARCHAR (100) NULL,
    [ESA_PM_Name]                     NVARCHAR (100) NULL,
    [ProjectOwnerId]                  NVARCHAR (100) NULL,
    [ProjectOwnerName]                NVARCHAR (100) NULL,
    [ProjectOwner_ESA_PM_Department]  NVARCHAR (50)  NULL,
    [EngagementDeliveryLead]          NVARCHAR (500) NULL,
    [PortfolioDeliveryLead]           NVARCHAR (500) NULL,
    [DeliveryExcellencePOC]           NVARCHAR (100) NULL,
    [Client_Practice]                 NVARCHAR (100) NULL);

