CREATE TYPE [dbo].[TVP_EditTicketMultiLingual] AS TABLE (
    [TimeTickerID]               BIGINT          NOT NULL,
    [TicketDescription]          NVARCHAR (MAX)  NULL,
    [ResolutionRemarks]          NVARCHAR (MAX)  NULL,
    [TicketSummary]              NVARCHAR (MAX)  NULL,
    [Comments]                   NVARCHAR (1000) NULL,
    [FlexField1]                 NVARCHAR (MAX)  NULL,
    [FlexField2]                 NVARCHAR (MAX)  NULL,
    [FlexField3]                 NVARCHAR (MAX)  NULL,
    [FlexField4]                 NVARCHAR (MAX)  NULL,
    [Category]                   NVARCHAR (MAX)  NULL,
    [Type]                       NVARCHAR (MAX)  NULL,
    [IsTicketDescriptionUpdated] BIT             NULL,
    [HasTicketDescriptionError]  BIT             NULL,
    [IsResolutionRemarksUpdated] BIT             NULL,
    [HasResolutionRemarksError]  BIT             NULL,
    [IsTicketSummaryUpdated]     BIT             NULL,
    [HasTicketSummaryError]      BIT             NULL,
    [IsCommentsUpdated]          BIT             NULL,
    [HasCommentsError]           BIT             NULL,
    [IsFlexField1Updated]        BIT             NULL,
    [HasFlexField1Error]         BIT             NULL,
    [IsFlexField2Updated]        BIT             NULL,
    [HasFlexField2Error]         BIT             NULL,
    [IsFlexField3Updated]        BIT             NULL,
    [HasFlexField3Error]         BIT             NULL,
    [IsFlexField4Updated]        BIT             NULL,
    [HasFlexField4Error]         BIT             NULL,
    [IsCategoryUpdated]          BIT             NULL,
    [HasCategoryError]           BIT             NULL,
    [IsTypeUpdated]              BIT             NULL,
    [HasTypeError]               BIT             NULL,
    [TicketType]                 INT             NOT NULL);

