CREATE TABLE [CII].[StgAvmFteRep] (
    [VerticalName]        VARCHAR (200)  NULL,
    [HorizontalName]      VARCHAR (200)  NULL,
    [SubHorizontalName]   VARCHAR (200)  NULL,
    [ParentCustomerId]    VARCHAR (200)  NULL,
    [AccountName]         VARCHAR (500)  NULL,
    [SubAccountName]      VARCHAR (500)  NULL,
    [ProjectId]           VARCHAR (200)  NULL,
    [ProjectName]         VARCHAR (200)  NULL,
    [GlobalMarket]        VARCHAR (200)  NULL,
    [BusinessName]        VARCHAR (200)  NULL,
    [OpportunityId]       INT            NULL,
    [OpporSubmitter]      VARCHAR (500)  NULL,
    [OpporSubmitterDept]  VARCHAR (2500) NULL,
    [OpporCreatedOn]      DATETIME       NULL,
    [Ideaid]              INT            NULL,
    [IdeaTitle]           VARCHAR (500)  NULL,
    [IdeaDesc]            VARCHAR (5000) NULL,
    [SubmitterId]         VARCHAR (200)  NULL,
    [SubmitterName]       VARCHAR (5000) NULL,
    [SubmitterDept]       VARCHAR (2000) NULL,
    [IdeaStatus]          VARCHAR (300)  NULL,
    [Module]              VARCHAR (200)  NULL,
    [EstTarLocatCust]     VARCHAR (100)  NULL,
    [EstFTERdnCust]       VARCHAR (100)  NULL,
    [EstAssoCntCust]      FLOAT (53)     NULL,
    [EstFTERelDateCust]   DATETIME       NULL,
    [EstEffortSavedCust]  FLOAT (53)     NULL,
    [EstCSFTECust]        FLOAT (53)     NULL,
    [EstTarLocatCog]      VARCHAR (100)  NULL,
    [EstFTERdnCog]        VARCHAR (100)  NULL,
    [EstAssoCntCog]       FLOAT (53)     NULL,
    [EstFTERelDateCog]    DATETIME       NULL,
    [EstEffortSavedCog]   FLOAT (53)     NULL,
    [EstCSFTECog]         FLOAT (53)     NULL,
    [ActTarLocatCust]     VARCHAR (100)  NULL,
    [ActFTERdnCust]       VARCHAR (100)  NULL,
    [ActAssoIDCust]       VARCHAR (100)  NULL,
    [ActLocationCust]     VARCHAR (100)  NULL,
    [ActDesignationCust]  VARCHAR (100)  NULL,
    [ActReleaseTagCust]   VARCHAR (500)  NULL,
    [ActRepAssoIDCust]    VARCHAR (100)  NULL,
    [ActRepAssoLocCust]   VARCHAR (100)  NULL,
    [ActRepAssoDesgnCust] VARCHAR (100)  NULL,
    [ActFTERelDateCust]   DATETIME       NULL,
    [ActEffortSavedCust]  FLOAT (53)     NULL,
    [ActCSFTECust]        FLOAT (53)     NULL,
    [ActTarLocatCog]      VARCHAR (100)  NULL,
    [ActFTERdnCog]        VARCHAR (100)  NULL,
    [ActAssoIDCog]        VARCHAR (100)  NULL,
    [ActLocationCog]      VARCHAR (100)  NULL,
    [ActDesignationCog]   VARCHAR (100)  NULL,
    [ActReleaseTagCog]    VARCHAR (500)  NULL,
    [ActRepAssoIDCog]     VARCHAR (100)  NULL,
    [ActRepAssoLocCog]    VARCHAR (100)  NULL,
    [ActRepAssoDesgnCog]  VARCHAR (100)  NULL,
    [ActFTERelDateCog]    DATETIME       NULL,
    [ActEffortSavedCog]   FLOAT (53)     NULL,
    [ActCSFTECog]         FLOAT (53)     NULL,
    [ImportedOn]          DATETIME       NULL,
    [SubVerticalName]     VARCHAR (200)  NULL,
    [CostPerResCog]       VARCHAR (200)  NULL,
    [CostPerResCust]      VARCHAR (200)  NULL,
    [RepCstPerResCust]    VARCHAR (200)  NULL,
    [RepCstPerResCog]     VARCHAR (200)  NULL
);

