CREATE TABLE [CII].[StgAVMRep] (
    [VerticalName]          VARCHAR (200)  NULL,
    [HorizontalName]        VARCHAR (200)  NULL,
    [SubHorizontalName]     VARCHAR (200)  NULL,
    [ParentCustomerId]      VARCHAR (20)   NULL,
    [AccountName]           VARCHAR (300)  NULL,
    [SubAccountName]        VARCHAR (300)  NULL,
    [ProjectId]             VARCHAR (20)   NULL,
    [ProjectName]           VARCHAR (300)  NULL,
    [GlobalMarket]          VARCHAR (300)  NULL,
    [BusinessName]          VARCHAR (300)  NULL,
    [OpportunityId]         INT            NULL,
    [OpporTitle]            VARCHAR (500)  NULL,
    [OpporDesc]             VARCHAR (5000) NULL,
    [OpporStatus]           VARCHAR (100)  NULL,
    [OpporWorkFlow]         VARCHAR (100)  NULL,
    [Ideaid]                INT            NULL,
    [IdeaTitle]             VARCHAR (250)  NULL,
    [IdeaDesc]              VARCHAR (5000) NULL,
    [IdeaCreatedOn]         DATETIME       NULL,
    [SubmitterId]           VARCHAR (100)  NULL,
    [SubmitterName]         VARCHAR (200)  NULL,
    [SubmitterDept]         VARCHAR (200)  NULL,
    [IdeaStatus]            VARCHAR (300)  NULL,
    [PendingWith]           VARCHAR (300)  NULL,
    [ApprovedBy]            VARCHAR (300)  NULL,
    [ApprovedOn]            DATETIME       NULL,
    [ProposalIsFTEAvail]    VARCHAR (10)   NULL,
    [themesource]           VARCHAR (300)  NULL,
    [DesignScenario]        VARCHAR (300)  NULL,
    [ServiceName]           VARCHAR (300)  NULL,
    [ThemeName]             VARCHAR (300)  NULL,
    [SuccessMet]            VARCHAR (300)  NULL,
    [UOM]                   VARCHAR (300)  NULL,
    [BusiOutcum]            VARCHAR (300)  NULL,
    [MetricsPerf]           VARCHAR (300)  NULL,
    [AutoUseCase]           VARCHAR (300)  NULL,
    [AutoSolnType]          VARCHAR (300)  NULL,
    [AutoMaturity]          VARCHAR (300)  NULL,
    [AssetReUse]            VARCHAR (10)   NULL,
    [AssetId]               VARCHAR (300)  NULL,
    [AssetName]             VARCHAR (300)  NULL,
    [IsSolnAvailable]       VARCHAR (10)   NULL,
    [CentralValue]          VARCHAR (50)   NULL,
    [StdDeviatBef]          FLOAT (53)     NULL,
    [BaseLineVal]           FLOAT (53)     NULL,
    [TargetVal]             FLOAT (53)     NULL,
    [PercentImp]            FLOAT (53)     NULL,
    [EndStateObj]           VARCHAR (MAX)  NULL,
    [Benefit]               VARCHAR (MAX)  NULL,
    [ProblemAreas]          VARCHAR (MAX)  NULL,
    [Levers]                VARCHAR (MAX)  NULL,
    [Service]               VARCHAR (MAX)  NULL,
    [InputSource]           VARCHAR (MAX)  NULL,
    [ProposalIsLSS]         VARCHAR (10)   NULL,
    [IsAutoCookbook]        VARCHAR (10)   NULL,
    [EstM1StartDate]        DATETIME       NULL,
    [EstM1EndDate]          DATETIME       NULL,
    [EstM2StartDate]        DATETIME       NULL,
    [EstM2EndDate]          DATETIME       NULL,
    [EstM3StartDate]        DATETIME       NULL,
    [EstM3EndDate]          DATETIME       NULL,
    [EstM4StartDate]        DATETIME       NULL,
    [EstM4EndDate]          DATETIME       NULL,
    [EstM5StartDate]        DATETIME       NULL,
    [EstM5EndDate]          DATETIME       NULL,
    [EstPullthroughRevenue] FLOAT (53)     NULL,
    [EstHDBenCalDtl]        VARCHAR (MAX)  NULL,
    [EstSDBenCalDtl]        VARCHAR (MAX)  NULL,
    [EstCOIDtl]             VARCHAR (MAX)  NULL,
    [EstQualBen]            VARCHAR (MAX)  NULL,
    [EstRevBenCylCust]      VARCHAR (100)  NULL,
    [EstRevBRCStDtCust]     DATETIME       NULL,
    [EstRevBRCEndDtCust]    DATETIME       NULL,
    [EstRevFisHDCust]       FLOAT (53)     NULL,
    [EstRevAnnHDCust]       FLOAT (53)     NULL,
    [EstCSBenCylCust]       VARCHAR (100)  NULL,
    [EstCSBRCStDtCust]      DATETIME       NULL,
    [EstCSBRCEndDtCust]     DATETIME       NULL,
    [EstCSFisHDCust]        FLOAT (53)     NULL,
    [EstCSAnnHDCust]        FLOAT (53)     NULL,
    [EstFTECRHDCust]        FLOAT (53)     NULL,
    [EstTtlCSFisHDCust]     FLOAT (53)     NULL,
    [EstCSFisSDCust]        FLOAT (53)     NULL,
    [EstCSAnnSDCust]        FLOAT (53)     NULL,
    [EstCOIFCust]           FLOAT (53)     NULL,
    [EstTotalCSFteCust]     FLOAT (53)     NULL,
    [EstRevBenCylCog]       VARCHAR (100)  NULL,
    [EstRevBRCStDtCog]      DATETIME       NULL,
    [EstRevBRCEndDtCog]     DATETIME       NULL,
    [EstRevFisHDCog]        FLOAT (53)     NULL,
    [EstRevAnnHDCog]        FLOAT (53)     NULL,
    [EstCSBenCylCog]        VARCHAR (100)  NULL,
    [EstCSBRCStDtCog]       DATETIME       NULL,
    [EstCSBRCEndDtCog]      DATETIME       NULL,
    [EstCSFisHDCog]         FLOAT (53)     NULL,
    [EstCSAnnHDCog]         FLOAT (53)     NULL,
    [EstFTECRHDCog]         FLOAT (53)     NULL,
    [EstTtlCSFisHDCog]      FLOAT (53)     NULL,
    [EstCSFisSDCog]         FLOAT (53)     NULL,
    [EstCSAnnSDCog]         FLOAT (53)     NULL,
    [EstCOIFCog]            FLOAT (53)     NULL,
    [EstTotalCSFteCog]      FLOAT (53)     NULL,
    [Solution]              VARCHAR (MAX)  NULL,
    [Benefits]              VARCHAR (MAX)  NULL,
    [CustMessaging]         VARCHAR (200)  NULL,
    [ActualValue]           FLOAT (53)     NULL,
    [StdDeviationAfter]     FLOAT (53)     NULL,
    [BillingModel]          VARCHAR (200)  NULL,
    [FinalIsLSS]            VARCHAR (10)   NULL,
    [FinalIsFTEAvail]       VARCHAR (10)   NULL,
    [ProjectStatus]         VARCHAR (200)  NULL,
    [ActM1StartDate]        DATETIME       NULL,
    [ActM1EndDate]          DATETIME       NULL,
    [ActM2StartDate]        DATETIME       NULL,
    [ActM2EndDate]          DATETIME       NULL,
    [ActM3StartDate]        DATETIME       NULL,
    [ActM3EndDate]          DATETIME       NULL,
    [ActM4StartDate]        DATETIME       NULL,
    [ActM4EndDate]          DATETIME       NULL,
    [ActM5StartDate]        DATETIME       NULL,
    [ActM5EndDate]          DATETIME       NULL,
    [ActHDBenCalDtl]        VARCHAR (MAX)  NULL,
    [ActSDBenCalDtl]        VARCHAR (MAX)  NULL,
    [ActCOIDtl]             VARCHAR (MAX)  NULL,
    [ActQualBen]            VARCHAR (MAX)  NULL,
    [ActPullthroughRevenue] FLOAT (53)     NULL,
    [ActRevBenCylCust]      VARCHAR (100)  NULL,
    [ActRevBRCStDtCust]     DATETIME       NULL,
    [ActRevBRCEndDtCust]    DATETIME       NULL,
    [ActRevFisHDCust]       FLOAT (53)     NULL,
    [ActRevAnnHDCust]       FLOAT (53)     NULL,
    [ActCSBenCylCust]       VARCHAR (100)  NULL,
    [ActCSBRCStDtCust]      DATETIME       NULL,
    [ActCSBRCEndDtCust]     DATETIME       NULL,
    [ActCSFisHDCust]        FLOAT (53)     NULL,
    [ActCSAnnHDCust]        FLOAT (53)     NULL,
    [ActFTECRHDCust]        FLOAT (53)     NULL,
    [ActTtlCSFisHDCust]     FLOAT (53)     NULL,
    [ActCSFisSDCust]        FLOAT (53)     NULL,
    [ActCSAnnSDCust]        FLOAT (53)     NULL,
    [ActCOIFCust]           FLOAT (53)     NULL,
    [ActTotalCSFteCust]     FLOAT (53)     NULL,
    [ActRevBenCylCog]       VARCHAR (100)  NULL,
    [ActRevBRCStDtCog]      DATETIME       NULL,
    [ActRevBRCEndDtCog]     DATETIME       NULL,
    [ActRevFisHDCog]        FLOAT (53)     NULL,
    [ActRevAnnHDCog]        FLOAT (53)     NULL,
    [ActCSBenCylCog]        VARCHAR (100)  NULL,
    [ActCSBRCStDtCog]       DATETIME       NULL,
    [ActCSBRCEndDtCog]      DATETIME       NULL,
    [ActCSFisHDCog]         FLOAT (53)     NULL,
    [ActCSAnnHDCog]         FLOAT (53)     NULL,
    [ActFTECRHDCog]         FLOAT (53)     NULL,
    [ActTtlCSFisHDCog]      FLOAT (53)     NULL,
    [ActCSFisSDCog]         FLOAT (53)     NULL,
    [ActCSAnnSDCog]         FLOAT (53)     NULL,
    [ActCOIFCog]            FLOAT (53)     NULL,
    [ActTotalCSFteCog]      FLOAT (53)     NULL,
    [MonthOfImplementation] VARCHAR (20)   NULL,
    [YearOfImplementation]  VARCHAR (20)   NULL,
    [ContributorId]         VARCHAR (MAX)  NULL,
    [ContributorName]       VARCHAR (MAX)  NULL,
    [ContributorPercent]    VARCHAR (MAX)  NULL,
    [Technology]            VARCHAR (MAX)  NULL,
    [ImportedOn]            DATETIME       NULL,
    [SubVerticalName]       VARCHAR (200)  NULL,
    [OpporSource]           VARCHAR (500)  NULL,
    [IdeaOpenClode]         VARCHAR (200)  NULL
);

