CREATE TABLE [MAS].[AppInventoryUpload] (
    [ApplicationName]          NVARCHAR (100) NULL,
    [ApplicationCode]          NVARCHAR (50)  NULL,
    [ApplicationShortName]     NVARCHAR (50)  NULL,
    [BusinessClusterName]      VARCHAR (MAX)  NULL,
    [CodeOwnerShip]            VARCHAR (MAX)  NULL,
    [BusinessCriticalityName]  VARCHAR (MAX)  NULL,
    [PrimaryTechnologyName]    VARCHAR (MAX)  NULL,
    [ProductMarketName]        NVARCHAR (MAX) NULL,
    [ApplicationDescription]   NVARCHAR (200) NULL,
    [ApplicationCommisionDate] DATETIME       NULL,
    [RegulatoryCompliantName]  VARCHAR (MAX)  NULL,
    [DebtcontrolScopeName]     VARCHAR (MAX)  NULL,
    [UserBase]                 NVARCHAR (50)  NULL,
    [SupportWindowName]        VARCHAR (MAX)  NULL,
    [Incallwdgreen]            NVARCHAR (50)  NULL,
    [Infraallwdgreen]          NVARCHAR (50)  NULL,
    [Incallwdamber]            NVARCHAR (50)  NULL,
    [Infraallwdamber]          NVARCHAR (50)  NULL,
    [Infoallwdamber]           NVARCHAR (50)  NULL,
    [Infoallwdgreen]           NVARCHAR (50)  NULL,
    [SupportCategoryName]      VARCHAR (MAX)  NULL,
    [OperatingSystem]          NVARCHAR (100) NULL,
    [ServerConfiguration]      NVARCHAR (100) NULL,
    [ServerOwner]              NVARCHAR (100) NULL,
    [LicenseDetails]           NVARCHAR (100) NULL,
    [DatabaseVersion]          NVARCHAR (100) NULL,
    [HostedEnvironmentName]    NVARCHAR (100) NULL,
    [isCognizant]              INT            NULL,
    [CustomerId]               VARCHAR (MAX)  NULL,
    [IsValid]                  VARCHAR (MAX)  NULL,
    [CloudServiceProvider]     NVARCHAR (500) NULL,
    [CloudModel]               NVARCHAR (20)  NULL,
    [Active]                   NVARCHAR (5)   NULL,
    [OtherTechnology]          NVARCHAR (50)  NULL,
    [OtherServiceProvider]     NVARCHAR (50)  NULL,
    [OtherWindow]              NVARCHAR (5)   NULL
);

