CREATE TABLE [BID].[RuleStatistics] (
    [ID]                          BIGINT          IDENTITY (1, 1) NOT NULL,
    [MonthYear]                   VARCHAR (10)    NOT NULL,
    [WorkflowType]                VARCHAR (10)    NOT NULL,
    [DealScope]                   VARCHAR (10)    NOT NULL,
    [AnalysisID]                  VARCHAR (20)    NOT NULL,
    [AccountID]                   INT             NULL,
    [AccountName]                 VARCHAR (100)   NULL,
    [BUID]                        SMALLINT        NULL,
    [BUName]                      VARCHAR (20)    NULL,
    [PrimaryText]                 VARCHAR (100)   NOT NULL,
    [SecondaryText]               VARCHAR (100)   NULL,
    [isAWBPerformed]              BIT             NULL,
    [AccuracyPercentage]          DECIMAL (10, 2) NULL,
    [PendingRulesCount]           INT             DEFAULT ((0)) NULL,
    [ApprovedRulesCount]          INT             DEFAULT ((0)) NULL,
    [OverriddenRulesCount]        INT             DEFAULT ((0)) NULL,
    [DormantRulesCount]           INT             DEFAULT ((0)) NULL,
    [MutedRulesCount]             INT             DEFAULT ((0)) NULL,
    [TotalRulesCount]             INT             DEFAULT ((0)) NULL,
    [AutoclassifiedTicketCount]   INT             NULL,
    [ManualclassifiedTicketCount] INT             NULL,
    [UnclassifiedTicketCount]     INT             NULL,
    [TotalTicketCount]            INT             NULL,
    [ScenarioFlag]                VARCHAR (20)    NULL,
    [IsDeleted]                   BIT             NOT NULL,
    [CreatedDate]                 DATETIME        NOT NULL,
    [CreatedBy]                   VARCHAR (10)    NOT NULL,
    [ModifiedDate]                DATETIME        NULL,
    [ModifiedBy]                  VARCHAR (10)    NULL,
    CONSTRAINT [PK_BID.RuleStatistcs] PRIMARY KEY CLUSTERED ([ID] ASC)
);

