CREATE TABLE [BID].[RulesMaster] (
    [RuleID]                              BIGINT         IDENTITY (1, 1) NOT NULL,
    [UseCase]                             NVARCHAR (500) NOT NULL,
    [SubGroup]                            NVARCHAR (500) NOT NULL,
    [DescWorkPattern]                     NVARCHAR (MAX) NOT NULL,
    [DescWorkSubPattern]                  NVARCHAR (MAX) NOT NULL,
    [ResolutionWorkPattern]               NVARCHAR (MAX) NOT NULL,
    [ResolutionWorkSubPattern]            NVARCHAR (MAX) NOT NULL,
    [DebtClassification]                  NVARCHAR (50)  NOT NULL,
    [AvoidableFlag]                       NVARCHAR (50)  NOT NULL,
    [AutomationPossibility]               NVARCHAR (50)  NOT NULL,
    [ProposedAutomationTool]              NVARCHAR (500) NULL,
    [AutomationImplFeasibility]           NVARCHAR (50)  NULL,
    [AutomationImplFeasibilityPercentage] NVARCHAR (10)  NULL,
    [EliminationFeasibilityPercentage]    NVARCHAR (10)  NULL,
    [LeftShiftFeasibility]                NVARCHAR (50)  DEFAULT ('') NULL,
    [LeftShiftPercentage]                 NVARCHAR (10)  NULL,
    [OptimizationFeasibility]             NVARCHAR (50)  NULL,
    [ServiceLevel]                        NVARCHAR (50)  DEFAULT ('') NULL,
    [DealScope]                           NVARCHAR (50)  NOT NULL,
    [DebtType]                            NVARCHAR (50)  DEFAULT ('combined') NULL,
    [IsDeleted]                           BIT            NOT NULL,
    [CreatedDate]                         DATETIME       NOT NULL,
    [CreatedBy]                           NVARCHAR (50)  NOT NULL,
    [ModifiedDate]                        DATETIME       NULL,
    [ModifiedBy]                          NVARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([RuleID] ASC)
);

