CREATE TABLE [BID].[RuleTransaction] (
    [RecordID]        BIGINT         IDENTITY (1, 1) NOT NULL,
    [RuleID]          BIGINT         NOT NULL,
    [AccountID]       BIGINT         DEFAULT (NULL) NULL,
    [AccountName]     NVARCHAR (500) DEFAULT (NULL) NULL,
    [BUID]            SMALLINT       DEFAULT (NULL) NULL,
    [BUName]          NVARCHAR (50)  DEFAULT (NULL) NULL,
    [RuleStatusInd]   SMALLINT       NOT NULL,
    [RuleReferanceID] BIGINT         DEFAULT ((0)) NOT NULL,
    [UCReferanceID]   BIGINT         DEFAULT ((0)) NOT NULL,
    [RuleLevel]       NVARCHAR (50)  NOT NULL,
    [Technology]      NVARCHAR (500) DEFAULT (NULL) NULL,
    [DebtType]        NVARCHAR (50)  DEFAULT ('combined') NULL,
    [IsDeleted]       BIT            NOT NULL,
    [TimesApplied]    BIGINT         DEFAULT ((0)) NULL,
    [ApprovedDate]    DATETIME       NULL,
    [ApprovedBy]      NVARCHAR (50)  NULL,
    [MutedDate]       DATETIME       NULL,
    [MutedBy]         NVARCHAR (50)  NULL,
    [IsDormant]       BIT            DEFAULT ((0)) NULL,
    [CreatedDate]     DATETIME       NOT NULL,
    [CreatedBy]       NVARCHAR (50)  NOT NULL,
    [TAModifiedDate]  DATETIME       NULL,
    [TAModifiedBy]    NVARCHAR (50)  NULL,
    [ModifiedDate]    DATETIME       NULL,
    [ModifiedBy]      NVARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([RecordID] ASC)
);

