CREATE TABLE [OPL].[Master_OPL_Projects] (
    [ID]                             NVARCHAR (255)  NOT NULL,
    [Market]                         NVARCHAR (255)  NULL,
    [Market Unit]                    NVARCHAR (255)  NULL,
    [Vertical]                       NVARCHAR (255)  NULL,
    [ESA Project ID]                 FLOAT (53)      NULL,
    [ESA_Project_Name]               NVARCHAR (255)  NULL,
    [Parent Account ID]              FLOAT (53)      NULL,
    [Parent_Account]                 NVARCHAR (255)  NULL,
    [Project Owning Unit]            NVARCHAR (255)  NULL,
    [BU]                             NVARCHAR (255)  NULL,
    [Client_ID]                      NVARCHAR (255)  NULL,
    [Solution_Area]                  NVARCHAR (255)  NULL,
    [Archetype]                      NVARCHAR (255)  NULL,
    [Work Category]                  NVARCHAR (3000) NULL,
    [Final Scope]                    NVARCHAR (255)  NULL,
    [Reason For Scope Change]        NVARCHAR (3000) NULL,
    [OrgProcessPackageName]          NVARCHAR (255)  NULL,
    [Main_Sub_Project_Flag]          NVARCHAR (255)  NULL,
    [Process Service Line]           NVARCHAR (255)  NULL,
    [Primary Market]                 NVARCHAR (255)  NULL,
    [Primary Market unit]            NVARCHAR (255)  NULL,
    [IsPerformanceSharingRestricted] NVARCHAR (255)  NULL,
    [ParentESAProjectID]             NVARCHAR (255)  NULL,
    [Primary BU]                     NVARCHAR (255)  NULL,
    [Project End Date]               NVARCHAR (255)  NULL,
    [Project Start Date]             NVARCHAR (255)  NULL,
    [Flag]                           NVARCHAR (255)  NULL,
    [CreatedDate]                    DATETIME        NULL,
    [CreatedBy]                      NVARCHAR (255)  NULL
);

