CREATE TABLE [AVL].[Effort_UseCaseDetails] (
    [UseCaseDetailID]                   BIGINT         IDENTITY (1, 1) NOT NULL,
    [SBUName]                           NVARCHAR (MAX) NULL,
    [AccountName]                       NVARCHAR (MAX) NULL,
    [ApplicationName]                   NVARCHAR (MAX) NULL,
    [Technology]                        NVARCHAR (MAX) NULL,
    [Domain]                            NVARCHAR (MAX) NULL,
    [BusinessProcess]                   NVARCHAR (MAX) NULL,
    [SubBusinessProcess]                NVARCHAR (MAX) NULL,
    [SBUGroup]                          NVARCHAR (MAX) NULL,
    [UseCaseID]                         NVARCHAR (MAX) NULL,
    [UseCaseTitle]                      NVARCHAR (MAX) NULL,
    [UseCaseDescription]                NVARCHAR (MAX) NULL,
    [Status]                            NVARCHAR (MAX) NULL,
    [Category]                          NVARCHAR (MAX) NULL,
    [SupportLevel]                      NVARCHAR (MAX) NULL,
    [AutomationFeasibility]             NVARCHAR (MAX) NULL,
    [AutomationUnanimousDecision]       NVARCHAR (MAX) NULL,
    [IfNotRecommendedReason]            NVARCHAR (MAX) NULL,
    [UseCaseSteps]                      NVARCHAR (MAX) NULL,
    [OverallEffortSpent]                NVARCHAR (MAX) NULL,
    [AverageNoofOccurrences]            NVARCHAR (MAX) NULL,
    [AverageEffortperOccurence]         NVARCHAR (MAX) NULL,
    [ProjectedMonthlyEffortSavings]     NVARCHAR (MAX) NULL,
    [FTESavings]                        NVARCHAR (MAX) NULL,
    [AutomationType]                    NVARCHAR (MAX) NULL,
    [ToolClassification]                NVARCHAR (MAX) NULL,
    [ToolName]                          NVARCHAR (MAX) NULL,
    [BOTSUsed]                          NVARCHAR (MAX) NULL,
    [TypeofBOT]                         NVARCHAR (MAX) NULL,
    [IdentifiedBy]                      NVARCHAR (MAX) NULL,
    [SpecialistId]                      NVARCHAR (MAX) NULL,
    [CurrentPhaseofInProgressUsecases]  NVARCHAR (MAX) NULL,
    [BenefitRealizationMonth]           NVARCHAR (MAX) NULL,
    [ImplementationDate]                NVARCHAR (MAX) NULL,
    [ImplementationMonth]               NVARCHAR (MAX) NULL,
    [ReferenceID]                       NVARCHAR (MAX) NULL,
    [AssociateName]                     NVARCHAR (MAX) NULL,
    [DevelopmentEffort]                 NVARCHAR (MAX) NULL,
    [CreatedOn]                         NVARCHAR (MAX) NULL,
    [ModifiedOn]                        NVARCHAR (MAX) NULL,
    [Tags]                              NVARCHAR (MAX) NULL,
    [NoiseEliminatedUseCaseTitle]       NVARCHAR (MAX) NULL,
    [NoiseEliminatedUseCaseDescription] NVARCHAR (MAX) NULL,
    [IsDeleted]                         BIT            NULL,
    [CreatedBy]                         NVARCHAR (50)  NULL,
    [ModifiedBy]                        NVARCHAR (50)  NULL,
    CONSTRAINT [PK_Effort_UseCaseDetails] PRIMARY KEY CLUSTERED ([UseCaseDetailID] ASC)
);

