CREATE TABLE [AVL].[MAS_ProjectDebtDetails] (
    [ProjectDebtId]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [ProjectID]                   BIGINT         NOT NULL,
    [EsaProjectID]                NVARCHAR (100) NOT NULL,
    [DebtEnablementDate]          DATETIME       NULL,
    [IsDeleted]                   BIT            NULL,
    [CreatedBy]                   NVARCHAR (50)  NULL,
    [CreatedDate]                 DATETIME       NULL,
    [ModifiedBy]                  NVARCHAR (50)  NULL,
    [ModifiedDate]                DATETIME       NULL,
    [DebtControlDate]             DATETIME       NULL,
    [DebtControlFlag]             CHAR (1)       NULL,
    [IsTicketApprovalNeeded]      CHAR (1)       NULL,
    [EnablementSuperAdminId]      NVARCHAR (100) NULL,
    [ControlSuperAdminId]         NVARCHAR (100) NULL,
    [IsAutoClassified]            CHAR (1)       NULL,
    [AutoClassificationDate]      DATETIME       NULL,
    [IsMLSignOff]                 CHAR (1)       NULL,
    [MLSignOffDate]               DATETIME       NULL,
    [MLSignOffUserId]             NVARCHAR (10)  NULL,
    [AutoClassifiedBy]            NVARCHAR (15)  NULL,
    [IsDDAutoClassified]          CHAR (1)       NULL,
    [IsDDAutoClassifiedDate]      DATETIME       NULL,
    [IsDDAutoClassifiedBy]        VARCHAR (50)   NULL,
    [IsCostTracked]               CHAR (1)       NULL,
    [DebtControlMethod]           CHAR (1)       NULL,
    [ISCLSIGNOFF]                 CHAR (1)       CONSTRAINT [Default_MAS_ProjectDebtDetails_ISCLSIGNOFF] DEFAULT (NULL) NULL,
    [CLSIGNOFFDATE]               DATETIME       CONSTRAINT [Default_MAS_ProjectDebtDetails_CLSIGNOFFDATE] DEFAULT (NULL) NULL,
    [CLSIGNOFFUSERID]             NVARCHAR (15)  CONSTRAINT [Default_MAS_ProjectDebtDetails_CLSIGNOFFUSERID] DEFAULT (NULL) NULL,
    [IsManual]                    CHAR (1)       NULL,
    [ManualDate]                  DATETIME       NULL,
    [IsCLAutoClassified]          CHAR (1)       NULL,
    [CLAutoClassifiedDate]        DATETIME       NULL,
    [CLAutoClassifiedBy]          NVARCHAR (30)  NULL,
    [OptionalAttributeType]       INT            DEFAULT (NULL) NULL,
    [IsAutoClassifiedInfra]       CHAR (1)       NULL,
    [AutoClassificationDateInfra] DATETIME       NULL,
    [IsMLSignOffInfra]            CHAR (1)       NULL,
    [MLSignOffDateInfra]          DATETIME       NULL,
    [MLSignOffUserIdInfra]        NVARCHAR (50)  NULL,
    [AutoClassifiedByInfra]       NVARCHAR (50)  NULL,
    [IsDDAutoClassifiedInfra]     CHAR (1)       NULL,
    [IsDDAutoClassifiedDateInfra] DATETIME       NULL,
    [IsDDAutoClassifiedByInfra]   NVARCHAR (50)  NULL,
    [NonDebtThresholdDays]        INT            NULL,
    [DDThresholdCount]            INT            NULL,
    [GracePeriod]                 SMALLINT       NULL,
    [IsRequireHistoricIncidents]  BIT            CONSTRAINT [df_IsRequireHistoricIncidents] DEFAULT (NULL) NULL,
    [IncidentHistoricDate]        DATETIME       CONSTRAINT [df_IncidentHistoricDate] DEFAULT (NULL) NULL,
    [IsRequireKticket]            BIT            NULL,
    CONSTRAINT [PK_MAS_ProjectDebtDetails] PRIMARY KEY CLUSTERED ([ProjectDebtId] ASC),
    CONSTRAINT [FK_MAS_ProjectDebtDetails_MAS_ProjectMaster] FOREIGN KEY ([ProjectID]) REFERENCES [AVL].[MAS_ProjectMaster] ([ProjectID]),
    CONSTRAINT [IX_MAS_ProjectDebtDetails] UNIQUE NONCLUSTERED ([ProjectID] ASC)
);

