CREATE TABLE [AVL].[ML_PRJ_InitialLearningStateInfra] (
    [ID]                               BIGINT        IDENTITY (1, 1) NOT NULL,
    [ProjectID]                        BIGINT        NOT NULL,
    [StartDate]                        DATETIME      NULL,
    [EndDate]                          DATETIME      NULL,
    [IsSamplingSentOrReceived]         NVARCHAR (50) NULL,
    [IsSamplingInProgress]             NVARCHAR (50) NULL,
    [IsMLSentOrReceived]               NVARCHAR (50) NULL,
    [SentBy]                           NVARCHAR (50) NULL,
    [SentOn]                           DATETIME      NULL,
    [ReceivedFrom]                     NVARCHAR (50) NULL,
    [ReceivedOn]                       DATETIME      NULL,
    [IsSDTicket]                       BIT           NULL,
    [IsDartTicket]                     BIT           NULL,
    [IsNoiseEliminationSentorReceived] NVARCHAR (50) NULL,
    [OptionalFieldupl]                 NVARCHAR (50) NULL,
    [IsNoiseSkipped]                   BIT           NULL,
    [IsRegenerated]                    BIT           NULL,
    [IsMultiLingualTranslated]         INT           NULL,
    [IsDeleted]                        BIT           NULL,
    [CreatedBy]                        NVARCHAR (50) NULL,
    [CreatedDate]                      DATETIME      NULL,
    [ModifiedBy]                       NVARCHAR (50) NULL,
    [ModifiedDate]                     DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

