CREATE TABLE [AVL].[ML_TRN_MLPatternValidation_CL] (
    [ID]                          BIGINT          IDENTITY (1, 1) NOT NULL,
    [InitialLearningID]           INT             NULL,
    [ProjectID]                   BIGINT          NULL,
    [ApplicationID]               BIGINT          NULL,
    [ApplicationTypeID]           INT             NULL,
    [TechnologyID]                INT             NULL,
    [TicketPattern]               NVARCHAR (MAX)  NULL,
    [MLResidualFlagID]            INT             NULL,
    [MLDebtClassificationID]      INT             NULL,
    [MLAvoidableFlagID]           INT             NULL,
    [MLCauseCodeID]               INT             NULL,
    [MLAccuracy]                  DECIMAL (18, 2) NULL,
    [TicketOccurence]             INT             NULL,
    [AnalystResidualFlagID]       INT             NULL,
    [AnalystResolutionCodeID]     INT             NULL,
    [AnalystCauseCodeID]          INT             NULL,
    [AnalystDebtClassificationID] INT             NULL,
    [AnalystAvoidableFlagID]      INT             NULL,
    [SMEComments]                 NVARCHAR (MAX)  NULL,
    [SMEResidualFlagID]           INT             NULL,
    [SMEDebtClassificationID]     INT             NULL,
    [SMEAvoidableFlagID]          INT             NULL,
    [SMECauseCodeID]              INT             NULL,
    [IsApprovedOrMute]            INT             NULL,
    [CreatedBy]                   NVARCHAR (20)   NULL,
    [CreatedDate]                 DATETIME        NULL,
    [ModifiedBy]                  NVARCHAR (20)   NULL,
    [ModifiedDate]                DATETIME        NULL,
    [IsDeleted]                   BIT             NULL,
    [Classifiedby]                NVARCHAR (1000) NULL,
    [ExpectedCompletionDate]      DATETIME        NULL,
    [ReasonforResidual]           INT             NULL,
    [IsCLSignOff]                 BIT             NULL,
    [MLResolutionCodeID]          INT             NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

