CREATE TABLE [AVL].[ML_TRN_MLPatternValidationInfra] (
    [ID]                          BIGINT          IDENTITY (1, 1) NOT NULL,
    [InitialLearningID]           BIGINT          NULL,
    [ProjectID]                   BIGINT          NULL,
    [TowerID]                     BIGINT          NULL,
    [TicketPattern]               NVARCHAR (4000) NULL,
    [MLResidualFlagID]            INT             NULL,
    [MLDebtClassificationID]      INT             NULL,
    [MLAvoidableFlagID]           INT             NULL,
    [MLCauseCodeID]               BIGINT          NULL,
    [MLAccuracy]                  DECIMAL (18, 2) NULL,
    [TicketOccurence]             INT             NULL,
    [AnalystResidualFlagID]       INT             NULL,
    [AnalystResolutionCodeID]     INT             NULL,
    [AnalystCauseCodeID]          INT             NULL,
    [AnalystDebtClassificationID] INT             NULL,
    [AnalystAvoidableFlagID]      INT             NULL,
    [SMEComments]                 NVARCHAR (4000) NULL,
    [SMEResidualFlagID]           INT             NULL,
    [SMEDebtClassificationID]     INT             NULL,
    [SMEAvoidableFlagID]          INT             NULL,
    [SMECauseCodeID]              BIGINT          NULL,
    [IsApprovedOrMute]            INT             NULL,
    [Classifiedby]                NVARCHAR (50)   NULL,
    [SMEResolutionCodeID]         INT             NULL,
    [ReasonForResidual]           INT             NULL,
    [ExpectedCompDate]            DATETIME        NULL,
    [MLResolutionCode]            BIGINT          NULL,
    [SubPattern]                  NVARCHAR (4000) DEFAULT ('0') NOT NULL,
    [AdditionalPattern]           NVARCHAR (4000) DEFAULT ('0') NOT NULL,
    [AdditionalSubPattern]        NVARCHAR (4000) DEFAULT ('0') NOT NULL,
    [OverridenPatternCount]       INT             NULL,
    [OverridenPatternTotalCount]  INT             NULL,
    [IsMLSignOff]                 INT             DEFAULT ((0)) NULL,
    [IsDeleted]                   BIT             NULL,
    [CreatedBy]                   NVARCHAR (50)   NULL,
    [CreatedDate]                 DATETIME        NULL,
    [ModifiedBy]                  NVARCHAR (50)   NULL,
    [ModifiedDate]                DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

