CREATE TABLE [AVL].[OnPremGovernanceMetrics] (
    [ID]                                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [AccountID]                                BIGINT          NOT NULL,
    [ProjectID]                                NVARCHAR (50)   NOT NULL,
    [Month]                                    TINYINT         NOT NULL,
    [Year]                                     SMALLINT        NOT NULL,
    [AllDebtClassifiedTicketCount]             INT             NULL,
    [EligibleTicketCountForDebtClassification] INT             NULL,
    [MLDDAutoClassifiedTicketCount]            INT             NULL,
    [BoTTicketCount]                           INT             NULL,
    [PartiallyAutomatedTicketCount]            INT             NULL,
    [ClosedATicketCount]                       INT             NULL,
    [ClosedHTicketCount]                       INT             NULL,
    [TotalEffortofChildATickets]               DECIMAL (18, 2) NULL,
    [CompletedMonthsofATicket]                 INT             NULL,
    [TotalEffortofChildHTickets]               DECIMAL (18, 2) NULL,
    [CompletedMonthsofHTicket]                 INT             NULL,
    [HChidTicketCount]                         INT             NULL,
    [OperationalTicketCount]                   INT             NULL,
    [KnowledgeTicketCount]                     INT             NULL,
    [FunctionalTicketCount]                    INT             NULL,
    [TechnicalTicketCount]                     INT             NULL,
    [EnvironmentalTicketCount]                 INT             NULL,
    [ResidualTicketCount]                      INT             NULL,
    [CreatedATicketCount]                      INT             NULL,
    [CreatedHTicketCount]                      INT             NULL,
    [InProgressATicketCount]                   INT             NULL,
    [InProgressHTicketCount]                   INT             NULL,
    [DormantATicketsClosedCount]               INT             NULL,
    [DormantHTicketsClosedCount]               INT             NULL,
    [CancelledATicketCount]                    INT             NULL,
    [CancelledHTicketCount]                    INT             NULL,
    [AvoidableIncidentCount]                   INT             NULL,
    [UnAvoidableIncidentCount]                 INT             NULL,
    [IsDeleted]                                BIT             NOT NULL,
    [CreatedBy]                                NVARCHAR (50)   NOT NULL,
    [CreatedDate]                              DATETIME        NOT NULL,
    [ModifiedBy]                               NVARCHAR (50)   NULL,
    [ModifiedDate]                             DATETIME        NULL,
    FOREIGN KEY ([AccountID]) REFERENCES [AVL].[Customer] ([CustomerID])
);

