CREATE TABLE [AVL].[TK_Mini_Sessions] (
    [SessionID]               BIGINT         IDENTITY (1, 1) NOT NULL,
    [UserID]                  BIGINT         NULL,
    [ProjectID]               BIGINT         NULL,
    [TicketID]                NVARCHAR (50)  NULL,
    [TicketDesc]              NVARCHAR (MAX) NULL,
    [TicketOpenDate]          DATETIME       NULL,
    [ApplicationID]           BIGINT         NULL,
    [ServiceID]               INT            NULL,
    [ActivityID]              INT            NULL,
    [TicketTypeMapID]         BIGINT         NULL,
    [PriorityMapID]           BIGINT         NULL,
    [TicketStatusMapID]       BIGINT         NULL,
    [StartTime]               DATETIME       NULL,
    [EndTime]                 DATETIME       NULL,
    [IsAuto]                  BIT            NULL,
    [Hours]                   INT            NULL,
    [Minutes]                 INT            NULL,
    [Seconds]                 INT            NULL,
    [IsProcessed]             INT            NULL,
    [EmployeeID]              NVARCHAR (50)  NULL,
    [RequestSource]           INT            NULL,
    [IsSDTicket]              BIT            NULL,
    [IsNonDelivery]           BIT            NULL,
    [NonDeliveryActivityType] INT            NULL,
    [IsDeleted]               BIT            NULL,
    [CreatedOn]               DATETIME       NULL,
    [CreatedBy]               NVARCHAR (50)  NULL,
    [ModifiedOn]              DATETIME       NULL,
    [ModifiedBy]              NVARCHAR (50)  NULL,
    [TimeTickerID]            BIGINT         NULL,
    [IsRunning]               BIT            NULL,
    [NonTicketDescription]    NVARCHAR (250) NULL,
    [UserCreatedTimeDate]     DATETIME       NULL,
    [SuggestedActivityName]   NVARCHAR (50)  NULL
);

