CREATE TABLE [AVL].[tk_trn_ticketdetail_EffortTillDate_Update] (
    [TimeTickerID]                 BIGINT          NOT NULL,
    [TicketID]                     NVARCHAR (50)   NOT NULL,
    [ApplicationID]                BIGINT          NOT NULL,
    [ProjectID]                    BIGINT          NULL,
    [AssignedTo]                   NVARCHAR (100)  NULL,
    [AssignmentGroup]              NVARCHAR (200)  NULL,
    [EffortTillDate]               DECIMAL (25, 2) NOT NULL,
    [ServiceID]                    INT             NOT NULL,
    [TicketDescription]            NVARCHAR (MAX)  NOT NULL,
    [IsDeleted]                    BIT             NOT NULL,
    [CauseCodeMapID]               BIGINT          NULL,
    [DebtClassificationMapID]      BIGINT          NULL,
    [ResidualDebtMapID]            BIGINT          NULL,
    [ResolutionCodeMapID]          BIGINT          NULL,
    [ResolutionMethodMapID]        BIGINT          NULL,
    [KEDBAvailableIndicatorMapID]  BIGINT          NULL,
    [KEDBUpdatedMapID]             BIGINT          NULL,
    [KEDBPath]                     NVARCHAR (250)  NULL,
    [PriorityMapID]                BIGINT          NULL,
    [ReleaseTypeMapID]             BIGINT          NULL,
    [SeverityMapID]                BIGINT          NULL,
    [TicketSourceMapID]            BIGINT          NULL,
    [TicketStatusMapID]            BIGINT          NULL,
    [TicketTypeMapID]              BIGINT          NULL,
    [BusinessSourceName]           NVARCHAR (50)   NULL,
    [Onsite_Offshore]              NVARCHAR (50)   NULL,
    [PlannedEffort]                DECIMAL (25, 2) NULL,
    [EstimatedWorkSize]            DECIMAL (25, 2) NULL,
    [ActualEffort]                 DECIMAL (25, 2) NULL,
    [ActualWorkSize]               DECIMAL (25, 2) NULL,
    [Resolvedby]                   NVARCHAR (50)   NULL,
    [Closedby]                     NVARCHAR (50)   NULL,
    [ElevateFlagInternal]          INT             NULL,
    [RCAID]                        VARCHAR (50)    NULL,
    [PlannedDuration]              DECIMAL (25, 2) NULL,
    [Actualduration]               DECIMAL (25, 2) NULL,
    [TicketSummary]                NVARCHAR (MAX)  NULL,
    [NatureoftheTicket]            NVARCHAR (50)   NULL,
    [Comments]                     NVARCHAR (1000) NULL,
    [RepeatedIncident]             NVARCHAR (50)   NULL,
    [RelatedTickets]               NVARCHAR (100)  NULL,
    [TicketCreatedBy]              NVARCHAR (4000) NULL,
    [SecondaryResources]           NVARCHAR (50)   NULL,
    [EscalatedFlagCustomer]        NVARCHAR (50)   NULL,
    [ReasonforRejection]           NVARCHAR (1000) NULL,
    [AvoidableFlag]                INT             NULL,
    [ReleaseDate]                  DATETIME        NULL,
    [TicketCreateDate]             DATETIME        NULL,
    [PlannedStartDate]             DATETIME        NULL,
    [PlannedEndDate]               DATETIME        NULL,
    [ActualStartdateTime]          DATETIME        NULL,
    [ActualEnddateTime]            DATETIME        NULL,
    [OpenDateTime]                 DATETIME        NULL,
    [StartedDateTime]              DATETIME        NULL,
    [WIPDateTime]                  DATETIME        NULL,
    [OnHoldDateTime]               DATETIME        NULL,
    [CompletedDateTime]            DATETIME        NULL,
    [ReopenDateTime]               DATETIME        NULL,
    [CancelledDateTime]            DATETIME        NULL,
    [RejectedDateTime]             DATETIME        NULL,
    [Closeddate]                   DATETIME        NULL,
    [AssignedDateTime]             DATETIME        NULL,
    [OutageDuration]               DECIMAL (25, 2) NULL,
    [MetResponseSLAMapID]          INT             NULL,
    [MetAcknowledgementSLAMapID]   INT             NULL,
    [MetResolutionMapID]           INT             NULL,
    [EscalationSLA]                INT             NULL,
    [TKBusinessID]                 BIGINT          NULL,
    [InscopeOutscope]              NVARCHAR (50)   NULL,
    [IsAttributeUpdated]           BIT             NULL,
    [NewStatusDateTime]            DATETIME        NULL,
    [IsSDTicket]                   BIT             NULL,
    [IsManual]                     BIT             NULL,
    [DARTStatusID]                 INT             NULL,
    [ResolutionRemarks]            NVARCHAR (MAX)  NULL,
    [ITSMEffort]                   DECIMAL (25, 2) NULL,
    [CreatedBy]                    NVARCHAR (50)   NOT NULL,
    [CreatedDate]                  DATETIME        NOT NULL,
    [LastUpdatedDate]              DATETIME        NOT NULL,
    [ModifiedBy]                   NVARCHAR (50)   NULL,
    [ModifiedDate]                 DATETIME        NULL,
    [IsApproved]                   BIT             NULL,
    [ReasonResidualMapID]          BIGINT          NULL,
    [ExpectedCompletionDate]       DATETIME        NULL,
    [ApprovedBy]                   NVARCHAR (100)  NULL,
    [DAPId]                        INT             NULL,
    [DebtClassificationMode]       BIGINT          NULL,
    [FlexField1]                   NVARCHAR (MAX)  NULL,
    [FlexField2]                   NVARCHAR (MAX)  NULL,
    [FlexField3]                   NVARCHAR (MAX)  NULL,
    [FlexField4]                   NVARCHAR (MAX)  NULL,
    [Category]                     NVARCHAR (MAX)  NULL,
    [Type]                         NVARCHAR (MAX)  NULL,
    [AssignmentGroupID]            BIGINT          NULL,
    [LastModifiedSource]           INT             NULL,
    [InitiatedSource]              INT             NULL,
    [IsPartiallyAutomated]         INT             NULL,
    [TicketDescriptionBasePattern] NVARCHAR (250)  NULL,
    [TicketDescriptionSubPattern]  NVARCHAR (250)  NULL,
    [ResolutionRemarksBasePattern] NVARCHAR (250)  NULL,
    [ResolutionRemarksSubPattern]  NVARCHAR (250)  NULL,
    [ServiceClassificationMode]    BIGINT          NOT NULL
);

