CREATE TABLE [AVL].[TM_TRN_TimesheetDetail_Test] (
    [TimeSheetDetailId]   BIGINT         IDENTITY (1, 1) NOT NULL,
    [TimesheetId]         BIGINT         NULL,
    [TimeTickerID]        BIGINT         NULL,
    [ApplicationID]       BIGINT         NULL,
    [TicketID]            NVARCHAR (100) NULL,
    [ShiftId]             INT            NULL,
    [IsNonTicket]         BIT            NULL,
    [ServiceId]           INT            NULL,
    [CategoryId]          INT            NULL,
    [ActivityId]          INT            NULL,
    [TicketTypeMapID]     INT            NULL,
    [Hours]               DECIMAL (5, 2) NULL,
    [Remarks]             NVARCHAR (MAX) NULL,
    [IsAttributeUpdated]  BIT            NULL,
    [TicketSourceID]      NVARCHAR (100) NULL,
    [IsSDTicket]          BIT            NULL,
    [ProjectId]           BIGINT         NULL,
    [IsDeleted]           BIT            NULL,
    [CreatedBy]           NVARCHAR (50)  NULL,
    [CreatedDateTime]     DATETIME       NULL,
    [ModifiedBy]          NVARCHAR (50)  NULL,
    [ModifiedDateTime]    DATETIME       NULL,
    [SuggestedActivityID] BIGINT         NULL
);

