CREATE TABLE [MS].[MAS_SUPPORTCATEGORY_Master] (
    [MainspringSUPPORTCATEGORYID]   INT            IDENTITY (1, 1) NOT NULL,
    [MainspringSUPPORTCATEGORYName] NVARCHAR (200) NULL,
    [IsDeleted]                     BIT            NULL,
    CONSTRAINT [PK_SUPPORTCATEGORY_Master] PRIMARY KEY CLUSTERED ([MainspringSUPPORTCATEGORYID] ASC) WITH (FILLFACTOR = 70)
);

