CREATE TABLE [PP].[Extended_ProjectDetails] (
    [ProjectDetailID]         BIGINT          IDENTITY (1, 1) NOT NULL,
    [ProjectID]               BIGINT          NOT NULL,
    [ProjectType]             INT             NULL,
    [OtherProjectType]        NVARCHAR (250)  NULL,
    [ProjectShortDescription] NVARCHAR (250)  NULL,
    [ContractValue]           INT             NULL,
    [BusinessDriver]          INT             NULL,
    [OtherBusinessDriver]     NVARCHAR (250)  NULL,
    [TechnicalDriver]         INT             NULL,
    [OtherTechnicalDriver]    NVARCHAR (250)  NULL,
    [IsKEDBOwned]             BIT             NULL,
    [NoOfPODS]                SMALLINT        NULL,
    [WorkItemSize]            SMALLINT        NULL,
    [SLACommitments]          DECIMAL (18, 2) NULL,
    [ProjectCommitmentType]   NVARCHAR (250)  NULL,
    [CommitmentValue]         NVARCHAR (250)  NULL,
    [VendorPresence]          BIT             NULL,
    [ServicesVendorTagging]   NVARCHAR (250)  NULL,
    [IsSubmitted]             BIT             NULL,
    [IsDeleted]               BIT             NOT NULL,
    [CreatedBy]               NVARCHAR (50)   NOT NULL,
    [CreatedDate]             DATETIME        NOT NULL,
    [ModifiedBy]              NVARCHAR (50)   NULL,
    [ModifiedDate]            DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([ProjectDetailID] ASC),
    FOREIGN KEY ([BusinessDriver]) REFERENCES [MAS].[PPAttributeValues] ([AttributeValueID]),
    FOREIGN KEY ([ContractValue]) REFERENCES [MAS].[PPAttributeValues] ([AttributeValueID]),
    FOREIGN KEY ([ProjectID]) REFERENCES [AVL].[MAS_ProjectMaster] ([ProjectID]),
    FOREIGN KEY ([ProjectType]) REFERENCES [MAS].[PPAttributeValues] ([AttributeValueID]),
    FOREIGN KEY ([TechnicalDriver]) REFERENCES [MAS].[PPAttributeValues] ([AttributeValueID])
);

