CREATE TABLE [PP].[MasterTableOfEOLDetails] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [InfraTypeId]          SMALLINT       NULL,
    [InfraDetailId]        INT            NULL,
    [InfraVersionId]       INT            NULL,
    [VendorName]           NVARCHAR (500) NULL,
    [IsOpenSource]         BIT            NULL,
    [Technology]           NVARCHAR (50)  NULL,
    [Update]               NVARCHAR (50)  NULL,
    [Edition]              NVARCHAR (50)  NULL,
    [LaunchedDate]         DATETIME       NULL,
    [EOL]                  DATETIME       NULL,
    [ExtendedDate]         DATE           NULL,
    [Source]               NVARCHAR (MAX) NULL,
    [Remarks]              NVARCHAR (MAX) NULL,
    [Latest Flag]          CHAR (1)       NULL,
    [IsUserCreated]        BIT            NOT NULL,
    [IsDeleted]            BIT            NULL,
    [CreatedBy]            NVARCHAR (50)  NULL,
    [CreatedDate]          DATETIME       NULL,
    [ModifiedBy]           NCHAR (10)     NULL,
    [ModifiedOn]           DATETIME       NULL,
    [ProductType]          NVARCHAR (500) NULL,
    [ProductName]          NCHAR (500)    NULL,
    [version]              NVARCHAR (50)  NULL,
    [licensedOrOpenSource] NVARCHAR (50)  NULL,
    [TBA/Expired]          NVARCHAR (20)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([InfraDetailId]) REFERENCES [PP].[TechCurrencyInfraDetail] ([InfraDetailId]),
    FOREIGN KEY ([InfraTypeId]) REFERENCES [PP].[TechCurrencyInfraType] ([InfraTypeId]),
    FOREIGN KEY ([InfraVersionId]) REFERENCES [PP].[TechCurrencyInfraVersion] ([InfraVersionId])
);

