CREATE TABLE [PP].[OplEsaData] (
    [ID]                                                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [ProjectID]                                              BIGINT          NOT NULL,
    [ProjectScope]                                           INT             NULL,
    [ServiceLinesInvolved]                                   NVARCHAR (100)  NULL,
    [ExecutionMethod]                                        INT             NULL,
    [Billability]                                            INT             NULL,
    [ProjectCategory]                                        NVARCHAR (250)  NULL,
    [DeliveryEngagementModel]                                NVARCHAR (100)  NULL,
    [ContractYear]                                           INT             NULL,
    [EndDate]                                                DATE            NULL,
    [FTE]                                                    DECIMAL (10, 2) NULL,
    [Onsite]                                                 DECIMAL (10, 2) NULL,
    [Offshore]                                               DECIMAL (10, 2) NULL,
    [Vertical]                                               NVARCHAR (250)  NULL,
    [OwningBU]                                               NVARCHAR (250)  NULL,
    [SkillDetails]                                           NVARCHAR (250)  NULL,
    [Projectowningunit]                                      NVARCHAR (250)  NULL,
    [HorizontalID]                                           BIGINT          NULL,
    [SubVertical]                                            NVARCHAR (250)  NULL,
    [Parentaccount]                                          NVARCHAR (250)  NULL,
    [IsDeleted]                                              BIT             NOT NULL,
    [CreatedBy]                                              NVARCHAR (50)   NOT NULL,
    [CreatedDate]                                            DATETIME        NOT NULL,
    [ModifiedBy]                                             NVARCHAR (50)   NULL,
    [ModifiedDate]                                           DATETIME        NULL,
    [Technology]                                             NVARCHAR (4000) NULL,
    [MarketUnit]                                             NVARCHAR (500)  NULL,
    [BU]                                                     NVARCHAR (500)  NULL,
    [Tracking Mode]                                          NVARCHAR (100)  NULL,
    [Is Performance data Sharing restricted as per contract] NVARCHAR (100)  NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC),
    FOREIGN KEY ([Billability]) REFERENCES [MAS].[PPAttributeValues] ([AttributeValueID]),
    FOREIGN KEY ([ExecutionMethod]) REFERENCES [MAS].[PPAttributeValues] ([AttributeValueID]),
    FOREIGN KEY ([HorizontalID]) REFERENCES [MAS].[PPHorizontal] ([HorizontalID]),
    FOREIGN KEY ([ProjectID]) REFERENCES [AVL].[MAS_ProjectMaster] ([ProjectID]),
    FOREIGN KEY ([ProjectScope]) REFERENCES [MAS].[PPAttributeValues] ([AttributeValueID])
);

