CREATE TABLE [LW].[RollupRules] (
    [TransRecordID]            BIGINT          NOT NULL,
    [RuleID]                   BIGINT          NOT NULL,
    [NewRuleReferanceID]       BIGINT          NOT NULL,
    [ApplensRuleID]            BIGINT          NULL,
    [RuleLevel]                NVARCHAR (50)   NULL,
    [ESAProjectID]             NVARCHAR (50)   NULL,
    [ESAProjectName]           NVARCHAR (50)   NULL,
    [ApplensProjectID]         BIGINT          NULL,
    [AppID]                    BIGINT          NULL,
    [AppName]                  NVARCHAR (100)  NULL,
    [AppType]                  NVARCHAR (50)   NULL,
    [Technology]               NVARCHAR (500)  NULL,
    [AccountID]                BIGINT          NULL,
    [AccountName]              NVARCHAR (100)  NULL,
    [BUID]                     SMALLINT        NULL,
    [BUName]                   NVARCHAR (100)  NULL,
    [CompetencyName]           NVARCHAR (500)  NULL,
    [BusinessProcessName]      NVARCHAR (500)  NULL,
    [LOB]                      NVARCHAR (500)  NULL,
    [AppInfra]                 NVARCHAR (20)   NULL,
    [RuleOccurance]            BIGINT          NULL,
    [InitialContinousFlag]     NVARCHAR (50)   NULL,
    [RuleConfidence]           DECIMAL (10, 2) NULL,
    [DescWorkPattern]          NVARCHAR (MAX)  NULL,
    [DescWorkSubPattern]       NVARCHAR (MAX)  NULL,
    [ResolutionWorkPattern]    NVARCHAR (MAX)  NULL,
    [ResolutionWorkSubPattern] NVARCHAR (MAX)  NULL,
    [AutomationFeasibility]    NVARCHAR (50)   NULL,
    [AppInfraFlag]             NVARCHAR (50)   NULL,
    [CauseCodeID]              BIGINT          NULL,
    [CauseCode]                NVARCHAR (500)  NULL,
    [ResolutionCodeID]         BIGINT          NULL,
    [ResolutionCode]           NVARCHAR (500)  NULL,
    [DebtClassificationID]     BIGINT          NULL,
    [DebtClassification]       NVARCHAR (50)   NULL,
    [AvoidableFlagID]          BIGINT          NULL,
    [AvoidableFlag]            NVARCHAR (50)   NULL,
    [ResidualDebtID]           BIGINT          NULL,
    [ResidualDebt]             NVARCHAR (50)   NULL,
    [IsDeleted]                BIT             NOT NULL,
    [CreatedDate]              DATETIME        NOT NULL,
    [CreatedBy]                NVARCHAR (50)   NOT NULL,
    [ModifiedDate]             DATETIME        NULL,
    [ModifiedBy]               NVARCHAR (50)   NULL
);

