CREATE TABLE [ADM].[ALM_TRN_Sprint_Details] (
    [SprintDetailsId]  BIGINT          IDENTITY (1, 1) NOT NULL,
    [SprintName]       NVARCHAR (1000) NOT NULL,
    [SprintDesc]       NVARCHAR (4000) NULL,
    [SprintOwner]      NVARCHAR (50)   NULL,
    [AssignedTo]       NVARCHAR (50)   NULL,
    [StatusId]         BIGINT          NULL,
    [SprintStartDate]  DATETIME        NULL,
    [SprintEndDate]    DATETIME        NULL,
    [ProjectId]        BIGINT          NOT NULL,
    [IsDeleted]        BIT             NOT NULL,
    [CreatedBy]        NVARCHAR (50)   NOT NULL,
    [CreatedDate]      DATETIME        NOT NULL,
    [ModifiedBy]       NVARCHAR (50)   NULL,
    [ModifiedDate]     DATETIME        NULL,
    [SprintId]         VARCHAR (25)    NULL,
    [SprintDuration]   INT             NULL,
    [PodId]            INT             NULL,
    [ADMSourceId]      BIGINT          NOT NULL,
    [ReleaseInfoId]    BIGINT          NULL,
    [SprintStageId]    BIGINT          DEFAULT ((5)) NOT NULL,
    [ActualStartDate]  DATE            NULL,
    [ActualEndDate]    DATE            NULL,
    [ReleaseDetailsId] BIGINT          NULL,
    CONSTRAINT [PK_ALM_TRN_Sprint_Details] PRIMARY KEY CLUSTERED ([SprintDetailsId] ASC),
    CONSTRAINT [FK_ALM_TRN_Sprint_Details_MAS_Source] FOREIGN KEY ([ADMSourceId]) REFERENCES [ADM].[MAS_Source] ([SourceId]),
    CONSTRAINT [FK_ALM_TRN_Sprint_Details_MAS_Source2] FOREIGN KEY ([SprintStageId]) REFERENCES [ADM].[MAS_Source] ([SourceId])
);

