CREATE TABLE [ADM].[ALM_TRN_WorkItem_Details_History] (
    [WorkItemHistoryId]    BIGINT          IDENTITY (1, 1) NOT NULL,
    [WorkItemDetailsId]    BIGINT          NOT NULL,
    [WorkTypeMapId]        BIGINT          NULL,
    [Project_Id]           BIGINT          NULL,
    [WorkItem_Id]          NVARCHAR (100)  NULL,
    [WorkItem_Title]       NVARCHAR (MAX)  NULL,
    [WorkItem_Description] NVARCHAR (MAX)  NULL,
    [StatusMapId]          BIGINT          NULL,
    [Tool_Activity]        NVARCHAR (250)  NULL,
    [Assignee]             NVARCHAR (50)   NULL,
    [ServiceId]            INT             NULL,
    [PriorityMapId]        BIGINT          NULL,
    [SeverityMapId]        BIGINT          NULL,
    [Risk]                 NVARCHAR (250)  NULL,
    [Order]                INT             NULL,
    [Actual_StartDate]     DATETIME        NULL,
    [Actual_EndDate]       DATETIME        NULL,
    [Planned_StartDate]    DATETIME        NULL,
    [Planned_EndDate]      DATETIME        NULL,
    [Estimation_Points]    NVARCHAR (100)  NULL,
    [Planned_Estimate]     DECIMAL (18, 2) NULL,
    [Actual_Effort]        DECIMAL (18, 2) NULL,
    [SprintDetailsId]      BIGINT          NULL,
    [Target_Date]          DATETIME        NULL,
    [Assignment_Group]     BIGINT          NULL,
    [ADMSourceId]          BIGINT          NULL,
    [ThemeMapId]           BIGINT          NULL,
    [Linked_ParentID]      NVARCHAR (100)  NULL,
    [Linked_ChildID]       BIGINT          NULL,
    [IsDeleted]            BIT             NULL,
    [CreatedBy]            NVARCHAR (50)   NULL,
    [CreatedDate]          DATETIME        NULL,
    [ModifiedDate]         DATETIME        NULL,
    [ModifiedBy]           NVARCHAR (50)   NULL,
    [Activity]             NVARCHAR (250)  NULL,
    [ApplicationId]        VARCHAR (50)    NULL,
    [BugPhaseTypeMapId]    SMALLINT        NULL,
    PRIMARY KEY CLUSTERED ([WorkItemHistoryId] ASC)
);

