CREATE TABLE [ADM].[TRN_ProjectMetricDetails] (
    [ProjectMetricDetailId] BIGINT         IDENTITY (1, 1) NOT NULL,
    [ProjectId]             BIGINT         NOT NULL,
    [MethodologyTypeId]     INT            NOT NULL,
    [ReportPeriod]          DATETIME       NOT NULL,
    [FrequencyId]           INT            NOT NULL,
    [BaseMeasureId]         INT            NOT NULL,
    [MetricId]              INT            NOT NULL,
    [BaseMeasureValue]      NVARCHAR (100) NULL,
    [MetricStartDate]       DATETIME       NULL,
    [MetricEndDate]         DATETIME       NULL,
    [IsDeleted]             BIT            NULL,
    [CreatedBy]             NVARCHAR (50)  NULL,
    [CreatedDate]           DATETIME       NULL,
    [ModifiedBy]            NVARCHAR (50)  NULL,
    [ModifiedDate]          DATETIME       NULL,
    [Status]                VARCHAR (15)   NULL,
    [SprintDetailsId]       BIGINT         NULL,
    [JobId]                 BIGINT         NULL,
    [ReleaseInfoId]         BIGINT         NULL,
    [UOMId]                 INT            NULL,
    [ReleaseDetailsId]      BIGINT         NULL,
    CONSTRAINT [PK_ADM.MS_TRN_ProjectMetricDetails] PRIMARY KEY CLUSTERED ([ProjectMetricDetailId] ASC),
    CONSTRAINT [FK_BaseMeasureId] FOREIGN KEY ([BaseMeasureId]) REFERENCES [MAS].[ADM_Metric_BaseMeasure] ([BaseMeasureId]),
    CONSTRAINT [FK_FrequencyId] FOREIGN KEY ([FrequencyId]) REFERENCES [MAS].[ADM_MetricMaster] ([MetricMasterId]),
    CONSTRAINT [FK_ProjectID] FOREIGN KEY ([ProjectId]) REFERENCES [AVL].[MAS_ProjectMaster] ([ProjectID]),
    CONSTRAINT [FK_TRN_MethodologyTypeId] FOREIGN KEY ([MethodologyTypeId]) REFERENCES [MAS].[PPAttributeValues] ([AttributeValueID]),
    CONSTRAINT [FK_TRN_MetricId] FOREIGN KEY ([MetricId]) REFERENCES [MAS].[ADM_Metric] ([MetricId]),
    CONSTRAINT [FK_TRN_ProjectMetricDetails_JobId] FOREIGN KEY ([JobId]) REFERENCES [MAS].[JobMaster] ([JobID]),
    CONSTRAINT [FK_TRN_ProjectMetricDetails_SprintDetailsId] FOREIGN KEY ([SprintDetailsId]) REFERENCES [ADM].[ALM_TRN_Sprint_Details] ([SprintDetailsId]),
    CONSTRAINT [FK_UOMId] FOREIGN KEY ([UOMId]) REFERENCES [MAS].[ADM_Metric_UOM] ([UOMId])
);

