CREATE TABLE [BOT].[MasterRepository] (
    [Id]                                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [BotName]                                NVARCHAR (100)  NOT NULL,
    [Overview]                               NVARCHAR (500)  NULL,
    [Description]                            NVARCHAR (4000) NULL,
    [BotTargetApplicationId]                 BIGINT          NULL,
    [TechnologyId]                           BIGINT          NULL,
    [BotCategoryId]                          BIGINT          NULL,
    [BotNatureId]                            BIGINT          NULL,
    [BotTypeId]                              BIGINT          NULL,
    [BotReusabilityId]                       BIGINT          NULL,
    [BusinessProcessId]                      BIGINT          NULL,
    [SubBusinessProcessId]                   BIGINT          NULL,
    [Rating]                                 NUMERIC (18, 1) NULL,
    [ContactDL]                              NVARCHAR (255)  NULL,
    [ServiceId]                              INT             NULL,
    [Author]                                 NVARCHAR (50)   NULL,
    [AutomationTechnology]                   NVARCHAR (50)   NULL,
    [DomainId]                               BIGINT          NULL,
    [DownloadCount]                          VARCHAR (255)   NULL,
    [Benefits]                               NVARCHAR (50)   NULL,
    [IsAvailableinCognizantAutomationCenter] VARCHAR (255)   NULL,
    [MakeVisible]                            BIT             NULL,
    [IsPackOnlyBot]                          VARCHAR (255)   NULL,
    [ProblemTypeId]                          BIGINT          NULL,
    [ActionType]                             NVARCHAR (50)   NULL,
    [ExecutionSubTypeId]                     BIGINT          NULL,
    [Source]                                 NVARCHAR (50)   NULL,
    [IsManuallyCreated]                      BIT             NULL,
    [BotStatusId]                            INT             NULL,
    [IsDeleted]                              BIT             NULL,
    [CreatedBy]                              NVARCHAR (50)   NULL,
    [CreatedOn]                              DATETIME        NULL,
    [ModifiedBy]                             NVARCHAR (50)   NULL,
    [ModifiedOn]                             DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

