CREATE TABLE [BOT].[QbotGoodnessScore] (
    [TimeTickerID]            BIGINT          NOT NULL,
    [English_Txt1]            BIT             NULL,
    [Action_Txt1]             BIT             NULL,
    [BlankText_Txt1]          BIT             NULL,
    [Context_Txt1]            BIT             NULL,
    [Source_Txt1]             BIT             NULL,
    [English_Txt2]            BIT             NULL,
    [Action_Txt2]             BIT             NULL,
    [BlankText_Txt2]          BIT             NULL,
    [Context_Txt2]            BIT             NULL,
    [Source_Txt2]             BIT             NULL,
    [English_Txt3]            BIT             NULL,
    [Action_Txt3]             BIT             NULL,
    [BlankText_Txt3]          BIT             NULL,
    [Context_Txt3]            BIT             NULL,
    [Source_Txt3]             BIT             NULL,
    [English_Txt4]            BIT             NULL,
    [Action_Txt4]             BIT             NULL,
    [BlankText_Txt4]          BIT             NULL,
    [Context_Txt4]            BIT             NULL,
    [Source_Txt4]             BIT             NULL,
    [Goodness_score_text1]    DECIMAL (25, 1) NULL,
    [Goodness_score_text2]    DECIMAL (25, 1) NULL,
    [Goodness_score_text3]    DECIMAL (25, 1) NULL,
    [Goodness_score_text4]    DECIMAL (25, 1) NULL,
    [Goodness_score_Combined] DECIMAL (25, 1) NULL,
    [IsDeleted]               BIT             NULL,
    [CreatedDate]             DATETIME        NOT NULL,
    [CreatedBy]               NVARCHAR (50)   NOT NULL,
    [ModifiedDate]            DATETIME        NULL,
    [ModifiedBy]              NVARCHAR (50)   NULL,
    FOREIGN KEY ([TimeTickerID]) REFERENCES [AVL].[TK_TRN_TicketDetail] ([TimeTickerID])
);

